### ISSUE TITLE
Can't update resource attribute  "ended_at=None"

### ISSUE THREAD

**Issue by qkxu** [gnocchixyz/gnocchi#1004]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Which version of Gnocchi are you using
gnocchi (4.0.4)
### How to reproduce your problem
update instance resource that set "None" value for resource attribute "ended_at"   by rest api 
### What is the result that you get
>>> _gnocchi.resource.update('instance', 'e0f29571-c173-4d5e-a801-ca610cfe96fc' ,{'ended_at': None})
2018-11-06 14:57:57.754 43527 CRITICAL ceilometer [-] Unhandled error: BadRequest: Invalid input: not a valid value for dictionary value @ data[u'ended_at'] (HTTP 400)
2018-11-06 14:57:57.754 43527 ERROR ceilometer Traceback (most recent call last):
2018-11-06 14:57:57.754 43527 ERROR ceilometer   File "<stdin>", line 1, in <module>
2018-11-06 14:57:57.754 43527 ERROR ceilometer   File "/usr/lib/python2.7/site-packages/gnocchiclient/v1/resource.py", line 111, in update
2018-11-06 14:57:57.754 43527 ERROR ceilometer     data=ujson.dumps(resource)).json()
2018-11-06 14:57:57.754 43527 ERROR ceilometer   File "/usr/lib/python2.7/site-packages/gnocchiclient/v1/base.py", line 49, in _patch
2018-11-06 14:57:57.754 43527 ERROR ceilometer     return self.client.api.patch(*args, **kwargs)
2018-11-06 14:57:57.754 43527 ERROR ceilometer   File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 316, in patch
2018-11-06 14:57:57.754 43527 ERROR ceilometer     return self.request(url, 'PATCH', **kwargs)
2018-11-06 14:57:57.754 43527 ERROR ceilometer   File "/usr/lib/python2.7/site-packages/gnocchiclient/client.py", line 52, in request
2018-11-06 14:57:57.754 43527 ERROR ceilometer     raise exceptions.from_response(resp, method)
2018-11-06 14:57:57.754 43527 ERROR ceilometer BadRequest: Invalid input: not a valid value for dictionary value @ data[u'ended_at'] (HTTP 400)

### What is result that you expected
I want set "None" value for ended_at.
![image](https://user-images.githubusercontent.com/26355838/48048568-e4a3ef80-e1d6-11e8-8c5f-01a6c4ef6d91.png)

**Comment by tobias-urdin** [comment]
Please provide more information and we can investigate further, until then closed.
