### ISSUE TITLE
gnocchi-api fails with AttributeError: 'module' object has no attribute 'V1Controller'

### ISSUE THREAD

**Issue by noonedeadpunk** [gnocchixyz/gnocchi#1010]
### Which version of Gnocchi are you using
```
root@openstack-sandbox:~# dpkg -l gnocchi-*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                          Version                             Architecture                        Description
+++-=============================================================-===================================-===================================-================================================================================================================================
ii  gnocchi-api                                                   4.2.4-0ubuntu1.1~cloud0             all                                 Metric as a Service - API daemon
ii  gnocchi-common                                                4.2.4-0ubuntu1.1~cloud0             all                                 Metric as a Service - common files
ii  gnocchi-metricd                                               4.2.4-0ubuntu1.1~cloud0             all                                 Metric as a Service - metric daemon
un  gnocchi-statsd                                                <none>                              <none>                              (no description available)
root@openstack-sandbox:~# 
```

### How to reproduce your problem
When I try to send request to gnocchi api, like "gnocchi resource list", I see the following trace in the apache error_log. Gnocchi has been installed on Ubuntu 16.04 via dist package from Queens repo (http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/queens/main amd64 Packages
)

### What is the result that you get
```
2018-12-27 21:09:27.029012 mod_wsgi (pid=3312847): Target WSGI script '/usr/bin/gnocchi-api' cannot be loaded as Python module.
2018-12-27 21:09:27.029058 mod_wsgi (pid=3312847): Exception occurred processing WSGI script '/usr/bin/gnocchi-api'.
2018-12-27 21:09:27.029086 Traceback (most recent call last):
2018-12-27 21:09:27.029112   File "/usr/bin/gnocchi-api", line 22, in <module>
2018-12-27 21:09:27.029163     application = app.load_app(api.prepare_service())
2018-12-27 21:09:27.029182   File "/usr/lib/python2.7/dist-packages/gnocchi/rest/app.py", line 173, in load_app
2018-12-27 21:09:27.029208     global_conf={'configkey': configkey})
2018-12-27 21:09:27.029232   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
2018-12-27 21:09:27.029261     return loadobj(APP, uri, name=name, **kw)
2018-12-27 21:09:27.029275   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
2018-12-27 21:09:27.029299     return context.create()
2018-12-27 21:09:27.029314   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
2018-12-27 21:09:27.029338     return self.object_type.invoke(self)
2018-12-27 21:09:27.029353   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 144, in invoke
2018-12-27 21:09:27.029381     **context.local_conf)
2018-12-27 21:09:27.029398   File "/usr/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
2018-12-27 21:09:27.029423     val = callable(*args, **kw)
2018-12-27 21:09:27.029440   File "/usr/lib/python2.7/dist-packages/paste/urlmap.py", line 31, in urlmap_factory
2018-12-27 21:09:27.029465     app = loader.get_app(app_name, global_conf=global_conf)
2018-12-27 21:09:27.029479   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 350, in get_app
2018-12-27 21:09:27.029510     name=name, global_conf=global_conf).create()
2018-12-27 21:09:27.029527   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
2018-12-27 21:09:27.029551     return self.object_type.invoke(self)
2018-12-27 21:09:27.029572   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 203, in invoke
2018-12-27 21:09:27.029596     app = context.app_context.create()
2018-12-27 21:09:27.029631   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
2018-12-27 21:09:27.029658     return self.object_type.invoke(self)
2018-12-27 21:09:27.029675   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
2018-12-27 21:09:27.029700     return fix_call(context.object, context.global_conf, **context.local_conf)
2018-12-27 21:09:27.029716   File "/usr/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
2018-12-27 21:09:27.029740     val = callable(*args, **kw)
2018-12-27 21:09:27.029758   File "/usr/lib/python2.7/dist-packages/gnocchi/rest/app.py", line 194, in app_factory
2018-12-27 21:09:27.029783     return _setup_app(root=local_conf.get('root'), **appconfig)
2018-12-27 21:09:27.029797   File "/usr/lib/python2.7/dist-packages/gnocchi/rest/app.py", line 182, in _setup_app
2018-12-27 21:09:27.029820     custom_renderers={"json": JsonRenderer}
2018-12-27 21:09:27.029835   File "/usr/local/lib/python2.7/dist-packages/pecan/__init__.py", line 86, in make_app
2018-12-27 21:09:27.029861     app = Pecan(root, **kw)
2018-12-27 21:09:27.029875   File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 832, in __init__
2018-12-27 21:09:27.029899     super(Pecan, self).__init__(*args, **kw)
2018-12-27 21:09:27.029916   File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 240, in __init__
2018-12-27 21:09:27.029940     root = self.__translate_root__(root)
2018-12-27 21:09:27.029956   File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 276, in __translate_root__
2018-12-27 21:09:27.029980     kallable = getattr(module, parts[-1])
2018-12-27 21:09:27.030010 AttributeError: 'module' object has no attribute 'V1Controller'

```

**Comment by noonedeadpunk** [comment]
Hi,

Sorry, found the problem - it was obsoleted /etc/gnocchi/api-paste.ini, which I've missed (as was trying to reference with https://github.com/gnocchixyz/gnocchi/blob/4.2.4/gnocchi/rest/api-paste.ini
