### ISSUE TITLE
gnocchi aggregates returns 400 while grouping by id

### ISSUE THREAD

**Issue by DilipRenkila** [gnocchixyz/gnocchi#1013]
I am running gnocchi version 4.2.5. I expected gnocchi to return aggregates while using groupby id option but it didn't seem to work in my case. It returns no metrics found 400 error. But i am able to get aggregates without groupby id . I am little bit confused to understand why it works like that. Can you guys explain me why it says no metrics ?

Without groupby id
```
root@ctrl1:~# gnocchi aggregates --resource-type volume --start "2019-01-01T00:00:00" --stop "2019-01-17T01:00:00" --fill 0 --granularity 300 "(metric volume.size max)" "project_id=2eea218eea984dd68f1378ea21c64b83"
+------------------------------------------------------+---------------------------+-------------+-------+
| name                                                 | timestamp                 | granularity | value |
+------------------------------------------------------+---------------------------+-------------+-------+
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T11:10:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T11:15:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T11:20:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T11:25:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T11:30:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T11:35:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T11:40:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T11:45:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T11:50:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T11:55:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T12:00:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T12:05:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T12:10:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T12:15:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T12:20:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T12:25:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T12:30:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T12:35:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T12:40:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T12:45:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T12:50:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T13:05:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T13:15:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T13:25:00+00:00 |       300.0 |   1.0 |
| ec1261cf-c372-4129-82a2-e299dd5ea202/volume.size/max | 2019-01-16T13:35:00+00:00 |       300.0 |   1.0 |

```

With groupby id 

```
root@ctrl1:~# gnocchi aggregates --resource-type volume --start "2019-01-01T00:00:00" --stop "2019-01-17T01:00:00" --groupby id --fill 0 --granularity 300 "(metric volume.size max)" "project_id=2eea218eea984dd68f1378ea21c64b83"
{u'cause': u'Metrics not found', u'detail': [u'volume.size']} (HTTP 400)
```

**Comment by chungg** [comment]
can you add `--debug` and paste the output? i guess remove any possible token/password/external accessible details.

**Comment by DilipRenkila** [comment]
```
$ gnocchi aggregates --resource-type volume --start "2019-01-01T00:00:00" --stop "2019-01-17T01:00:00" --groupby id --fill 0 --granularity 300 "(metric volume.size max)" "project_id=2eea218eea984dd68f1378ea21c64b83"

Starting new HTTP connection (1): internal.sto1.cloud.linserv.se
http://internal.sto1.cloud.linserv.se:8041 "POST /v1/aggregates?details=False&granularity=300&groupby=id&start=2019-01-01T00%3A00%3A00&stop=2019-01-17T01%3A00%3A00 HTTP/1.1" 400 111
RESP: [400] Content-Length: 111 Content-Type: application/json Date: Fri, 18 Jan 2019 08:56:54 GMT Server: Apache/2.4.29 (Ubuntu)
RESP BODY: {"code": 400, "title": "Bad Request", "description": {"cause": "Metrics not found", "detail": ["volume.size"]}}
{u'cause': u'Metrics not found', u'detail': [u'volume.size']} (HTTP 400)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/lib/python2.7/dist-packages/cliff/display.py", line 116, in run
    column_names, data = self.take_action(parsed_args)
  File "/usr/lib/python2.7/dist-packages/gnocchiclient/v1/aggregates_cli.py", line 57, in take_action
    groupby=parsed_args.groupby,
  File "/usr/lib/python2.7/dist-packages/gnocchiclient/v1/aggregates.py", line 72, in fetch
    data=json.dumps(data)).json()
  File "/usr/lib/python2.7/dist-packages/gnocchiclient/v1/base.py", line 41, in _post
    return self.client.api.post(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 334, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python2.7/dist-packages/gnocchiclient/client.py", line 52, in request
    raise exceptions.from_response(resp, method)
BadRequest: {u'cause': u'Metrics not found', u'detail': [u'volume.size']} (HTTP 400)
Traceback (most recent call last):
  File "/usr/bin/gnocchi", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/gnocchiclient/shell.py", line 251, in main
    return GnocchiShell().run(args)
  File "/usr/lib/python2.7/dist-packages/cliff/app.py", line 279, in run
    result = self.run_subcommand(remainder)
  File "/usr/lib/python2.7/dist-packages/cliff/app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/lib/python2.7/dist-packages/cliff/display.py", line 116, in run
    column_names, data = self.take_action(parsed_args)
  File "/usr/lib/python2.7/dist-packages/gnocchiclient/v1/aggregates_cli.py", line 57, in take_action
    groupby=parsed_args.groupby,
  File "/usr/lib/python2.7/dist-packages/gnocchiclient/v1/aggregates.py", line 72, in fetch
    data=json.dumps(data)).json()
  File "/usr/lib/python2.7/dist-packages/gnocchiclient/v1/base.py", line 41, in _post
    return self.client.api.post(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 334, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python2.7/dist-packages/gnocchiclient/client.py", line 52, in request
    raise exceptions.from_response(resp, method)
gnocchiclient.exceptions.BadRequest: {u'cause': u'Metrics not found', u'detail': [u'volume.size']} (HTTP 400)

```

**Comment by DilipRenkila** [comment]
curl -g -i -X POST http://internal.sto1.cloud.linserv.se:8041/v1/aggregates?details=False&granularity=300&groupby=id&start=2019-01-01T00%3A00%3A00&stop=2019-01-17T01%3A00%3A00 -H "Accept: application/json, */*" -H "Content-Type: application/json" -H "User-Agent: gnocchi keystoneauth1/3.10.0 python-requests/2.19.1 CPython/2.7.15rc1" -H "X-Auth-Token: " -d '{"operations": "(metric volume.size max)", "search": "project_id=2eea218eea984dd68f1378ea21c64b83", "resource_type": "volume"}'

**Comment by chungg** [comment]
i has no idea at quick glance. i don't see how groupby=id would throw that error specifically. will need to look at it over weekend unless someone else knows.

**Comment by DilipRenkila** [comment]
I think its due to [](https://github.com/gnocchixyz/gnocchi/blob/4.2.5/gnocchi/rest/aggregates/api.py#L308)

**Comment by chungg** [comment]
i'm not sure why it returns `Metrics not found` for you if it returns metrics when you don't add groupby. you may need to debug this yourself. 

specifically, it seems like https://github.com/gnocchixyz/gnocchi/blob/4.2.5/gnocchi/rest/aggregates/api.py#L231-L234 is not returning values for you.

maybe try adding logging to gather more information

**Comment by DilipRenkila** [comment]
a particular resource of type volume has only snapshot.size metric . Thats causing the error. That resource don't posses volume.size metric. Is this the desired behavior of gnocchi api ?

**Comment by chungg** [comment]
yeah. that was one of my guesses. thanks for confirming!

i'm not sure this is desired. it should at the very least tell you which resources don't have the metric. personally, i think we should just remove those resources but i guess there's an argument whether it's safe to do this silently.

**Comment by obi12341** [comment]
hello,
i have the exact same problem. I have a lot of resources which just contain snapshot.size and getting the same errors. Is it possible to prevent this behavior?

**Comment by chungg** [comment]
you could probably just create the metric definition[1] even though no datapoints will every be pushed to it as workaround. you would need to do it for all resources missing it though.

[1] https://gnocchi.xyz/rest.html#create

**Comment by obi12341** [comment]
thanks for your suggestion. i am looking into it, but looks like a really hacky workaround to me :P

**Comment by chungg** [comment]
lol, never said it was elegant.

i have a patch up. you can try testing it to see if it resolves your issue. it will return any group that has the required metric and if all groups don't have the metric, only then will it return the 400 error
