### ISSUE TITLE
metric is not handled by Gnocchi

### ISSUE THREAD

**Issue by universcom** [gnocchixyz/gnocchi#1040]
i enable LBaaS v2 on openstack queens. 
i need get feature of LBaaS v2 from ceilometer. 
i add needed parameter to pollster.yaml file like below: 
```
---
sources:
    - name: some_pollsters
      interval: 10
      meters:
        - cpu
        - cpu_l3_cache
        - memory.usage
        - network.incoming.bytes
        - network.incoming.packets
        - network.outgoing.bytes
        - network.outgoing.packets
        - disk.device.read.bytes
        - disk.device.read.requests
        - disk.device.write.bytes
        - disk.device.write.requests
        - hardware.cpu.util
        - hardware.memory.used
        - hardware.memory.total
        - hardware.memory.buffer
        - hardware.memory.cached
        - hardware.memory.swap.avail
        - hardware.memory.swap.total
        - hardware.system_stats.io.outgoing.blocks
        - hardware.system_stats.io.incoming.blocks
        - hardware.network.ip.incoming.datagrams
    - name: lb_pollsters
      interval: 1
      meters:
        - network.services.lb.outgoing.bytes
        - network.services.lb.incoming.bytes
        - network.services.lb.pool
        - network.services.lb.listener
        - network.services.lb.member
        - network.services.lb.health_monitor
        - network.services.lb.loadbalancer
        - network.services.lb.total.connections
        - network.services.lb.active.connections
```

in ceilomter log: 

```
2019-07-24 20:52:05.877 15035 WARNING ceilometer.publisher.gnocchi [-] metric network.services.lb.loadbalancer is not handled by Gnocchi
2019-07-24 20:52:08.302 15035 WARNING ceilometer.publisher.gnocchi [-] metric network.services.lb.health_monitor is not handled by Gnocchi
2019-07-24 20:52:09.095 15035 WARNING ceilometer.publisher.gnocchi [-] metric network.services.lb.total.connections is not handled by Gnocchi
2019-07-24 20:52:09.883 15035 WARNING ceilometer.publisher.gnocchi [-] metric network.services.lb.listener is not handled by Gnocchi
2019-07-24 20:52:09.899 15035 WARNING ceilometer.publisher.gnocchi [-] metric network.services.lb.incoming.bytes is not handled by Gnocchi
2019-07-24 20:52:10.831 15035 WARNING ceilometer.publisher.gnocchi [-] metric network.services.lb.pool is not handled by Gnocchi
2019-07-24 20:52:10.834 15035 WARNING ceilometer.publisher.gnocchi [-] metric network.services.lb.active.connections is not handled by Gnocchi
2019-07-24 20:52:10.834 15035 WARNING ceilometer.publisher.gnocchi [-] metric network.services.lb.outgoing.bytes is not handled by Gnocchi
```
in gnocchi log: 

```
2019-07-24 20:51:57.738559   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 250, in wrapper
2019-07-24 20:51:57.738566   File "/usr/lib/python2.7/dist-packages/tooz/coordination.py", line 186, in _beat_forever_until_stopped
2019-07-24 20:51:57.738573 <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'StopWatch'
2019-07-24 20:51:57.829859 Exception in thread Thread-1 (most likely raised during interpreter shutdown):
2019-07-24 20:51:57.829895 Traceback (most recent call last):
2019-07-24 20:51:57.829906   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2019-07-24 20:51:57.829914   File "/usr/lib/python2.7/threading.py", line 754, in run
2019-07-24 20:51:57.829919   File "/usr/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 250, in wrapper
2019-07-24 20:51:57.829927   File "/usr/lib/python2.7/dist-packages/tooz/coordination.py", line 186, in _beat_forever_until_stopped
2019-07-24 20:51:57.829938 <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'StopWatch'
```
how i can fix this problem and get LBaaS V2 parameter from gnnochi? 
tancks

**Comment by jd** [comment]
Ceilometer issue.

Your `gnocchi.log` shows an error that happens during shutdown, it can be ignored. It's a bug in tooz probably.

**Comment by universcom** [comment]
tanks dear jd for your help 
problem solved. 
i should update gnocchi_client.py and /publisher/data/gnocchi_resources.yaml in /usr/lib/python2.7/dist-packages/ceilometer directory. 
below links help us: 
(https://docs.openstack.org/ceilometer/latest/contributor/new_resource_types.html)
