### ISSUE TITLE
gnicchi upgrade fails when using s3 driver for  aggregate storage when bucket is present

### ISSUE THREAD

**Issue by manuvakery1** [gnocchixyz/gnocchi#1085]
### Which version of Gnocchi are you using
gnocchi 7.0.4 (centos-release-openstack-train)
### How to reproduce your problem
1. use s3 driver for gnocchi aggregate storage 
2.  perform `gnocchi-upgrade` multiple times
### What is the result that you get
```
2020-11-23 11:55:38,990 [13618] CRITICAL root: Traceback (most recent call last):
  File "/bin/gnocchi-upgrade", line 11, in <module>
    load_entry_point('gnocchi==4.3.4', 'console_scripts', 'gnocchi-upgrade')()
  File "/usr/lib/python2.7/site-packages/gnocchi/cli/manage.py", line 73, in upgrade
    s.upgrade()
  File "/usr/lib/python2.7/site-packages/gnocchi/storage/s3.py", line 90, in upgrade
    s3.create_bucket(self.s3, self._bucket_name, self._region_name)
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 292, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 319, in iter
    return fut.result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 361, in call
    result = fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/gnocchi/common/s3.py", line 65, in create_bucket
    return conn.create_bucket(Bucket=name, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
BucketAlreadyOwnedByYou: An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.
```

### What is result that you expected
`BucketAlreadyOwnedByYou` exception should be handled gracefully

**Comment by manuvakery1** [comment]
I this the check [here](https://github.com/gnocchixyz/gnocchi/blob/cb8a0e46c8815e0bd1dc25ff01c58eb9debe79a0/gnocchi/storage/s3.py#L92) should be changed as follows
```
try:
            s3.create_bucket(self.s3, self._bucket_name, self._region_name)
        except botocore.exceptions.ClientError as e:
            if e.response['Error'].get('Code') != "BucketAlreadyOwnedByYou":
                raise
```
helpful [link](https://aws.amazon.com/premiumsupport/knowledge-center/s3-error-bucket-already-exists/)
