### ISSUE TITLE
Redis closes the connection

### ISSUE THREAD

**Issue by mrunge** [gnocchixyz/gnocchi#1120]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Which version of Gnocchi are you using
gnocchi 4.3.4

### How to reproduce your problem
3 controllers, with redis master/slaves behing haproxy. Below error messages happen at random times, about 10 times per hour.

### What is the result that you get
```
2021-02-19 07:02:00,513 [27] ERROR    gnocchi.cli.metricd: Error while listening for new measures notification, retrying
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gnocchi/cli/metricd.py", line 186, in _fill_sacks_to_process
    for sack in self.incoming.iter_on_sacks_to_process():
  File "/usr/lib/python3.6/site-packages/gnocchi/incoming/redis.py", line 186, in iter_on_sacks_to_process
    for message in p.listen():
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 3285, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 3185, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 3159, in _execute
    return command(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/redis/connection.py", line 699, in read_response
    response = self._parser.read_response()
  File "/usr/lib/python3.6/site-packages/redis/connection.py", line 309, in read_response
    response = self._buffer.readline()
  File "/usr/lib/python3.6/site-packages/redis/connection.py", line 241, in readline
    self._read_from_socket()
  File "/usr/lib/python3.6/site-packages/redis/connection.py", line 186, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
2021-02-19 07:02:00,524 [27] DEBUG    gnocchi.chef: Processing measures for sack incoming128-4

```

This report is to track this issue. I have opened https://github.com/gnocchixyz/gnocchi/pull/1119 to fix this.

**Comment by jd** [comment]
This is not a big deal per say as it'll reconnect and retry to listen for new connection anyway.

A good fix here would be to catch the exception and retry `iter_on_sacks_to_process` using tenacity.
