### ISSUE TITLE
Redis sentinel 6.0 ssl support

### ISSUE THREAD

**Issue by tomm144** [gnocchixyz/gnocchi#1122]
Hi,
does gnocchi have support for Redis Sentinel connect trough ssl ?
Seems like no.
Or i'm doing it somehow wrong?
Thanks.

### Which version of Gnocchi are you using
4.3.3
### How to reproduce your problem
change in gnocchi.conf coordination_url .
coordination_url = redis://<sentinel_ip>:26379?sentinel=mymaster&ssl=True

### What is the result that you get
I got a ton of error messages like this:
2021-02-26 15:15:03,486 [59844] ERROR    gnocchi.utils: Unable to initialize coordination driver
Traceback (most recent call last):
  File "/openstack/venvs/gnocchi-18.1.9/lib/python2.7/site-packages/tenacity/__init__.py", line 333, in call
    result = fn(*args, **kwargs)
  File "/openstack/venvs/gnocchi-18.1.9/lib/python2.7/site-packages/gnocchi/cli/metricd.py", line 45, in get_coordinator_and_start
    coord.start(start_heart=True)
  File "/openstack/venvs/gnocchi-18.1.9/lib/python2.7/site-packages/tooz/coordination.py", line 687, in start
    super(CoordinationDriverWithExecutor, self).start(start_heart)
  File "/openstack/venvs/gnocchi-18.1.9/lib/python2.7/site-packages/tooz/coordination.py", line 423, in start
    self._start()
  File "/openstack/venvs/gnocchi-18.1.9/lib/python2.7/site-packages/tooz/drivers/redis.py", line 449, in _start
    self._server_info = self._client.info()
  File "/openstack/venvs/gnocchi-18.1.9/lib/python2.7/site-packages/redis/client.py", line 760, in info
    return self.execute_command('INFO')
  File "/openstack/venvs/gnocchi-18.1.9/lib/python2.7/site-packages/redis/client.py", line 665, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/openstack/venvs/gnocchi-18.1.9/lib/python2.7/site-packages/redis/connection.py", line 965, in get_connection
    connection = self.make_connection()
  File "/openstack/venvs/gnocchi-18.1.9/lib/python2.7/site-packages/redis/connection.py", line 983, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/openstack/venvs/gnocchi-18.1.9/lib/python2.7/site-packages/redis/sentinel.py", line 23, in __init__
    super(SentinelManagedConnection, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl'

### What is result that you expected
successfull connect with ssl params.

**Comment by mrunge** [comment]
Gnocchi uses redis-py through tooz. I see an open PR on redis-py
https://github.com/andymccurdy/redis-py/pull/1419 which is supposed to implement that feature.
