### ISSUE TITLE
gnocchi-upgrade errors on initial run

### ISSUE THREAD

**Issue by jspeckman** [gnocchixyz/gnocchi#1180]
New install of gnocchi produces the following when running gnocci-upgade for the first time:
```
su -s /bin/bash gnocchi -c "gnocchi-upgrade"
2021-10-26 23:30:32,465 [2637067] INFO     gnocchi.service: Gnocchi version 4.3.5
2021-10-26 23:30:32,750 [2637067] CRITICAL root: Traceback (most recent call last):
  File "/bin/gnocchi-upgrade", line 11, in <module>
    load_entry_point('gnocchi==4.3.5', 'console_scripts', 'gnocchi-upgrade')()
  File "/usr/lib/python3.6/site-packages/gnocchi/cli/manage.py", line 67, in upgrade
    index = indexer.get_driver(conf)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.6/site-packages/tenacity/__init__.py", line 348, in iter
    if not (is_explicit_retry or self.retry(retry_state=retry_state)):
TypeError: __call__() got an unexpected keyword argument 'retry_state'
```

I am using mysql for the indexer
The install is on CentOS 8 with OpenStack Ussuri

**Comment by chungg** [comment]
hmm.. are you sure it's using 5.1.1? the line numbers from your stacktrace seems to match closer to tenancity 8.0.0+

**Comment by jspeckman** [comment]
Thanks for the tip.
It turns out I had both versions installed, and version 8 was being used instead of 5.1.1
