### ISSUE TITLE
Setup gnocchi in recent devstack fails

### ISSUE THREAD

**Issue by mrunge** [gnocchixyz/gnocchi#1258]
```
2022-06-20 10:50:35,005 [84965] CRITICAL root: Traceback (most recent call last):
  File "/usr/local/bin/gnocchi-upgrade", line 33, in <module>
    sys.exit(load_entry_point('gnocchi', 'console_scripts', 'gnocchi-upgrade')())
  File "/opt/stack/devstack/src/gnocchi/gnocchi/cli/manage.py", line 69, in upgrade
    index.upgrade()
  File "/opt/stack/devstack/src/gnocchi/gnocchi/indexer/sqlalchemy.py", line 349, in upgrade
    with self.facade.writer_connection() as connection:
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 1054, in _transaction_scope
    with current._produce_block(
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 621, in _connection
    self.connection = self.factory._create_connection(
  File "/usr/local/lib/python3.9/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 403, in _create_connection
    self._start()
  File "/usr/local/lib/python3.9/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 504, in _start
    self._setup_for_connection(
  File "/usr/local/lib/python3.9/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 529, in _setup_for_connection
    engine = engines.create_engine(
  File "/usr/local/lib/python3.9/site-packages/debtcollector/renames.py", line 43, in decorator
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/oslo_db/sqlalchemy/engines.py", line 211, in create_engine
    test_conn = _test_connection(engine, max_retries, retry_interval)
  File "/usr/local/lib/python3.9/site-packages/oslo_db/sqlalchemy/engines.py", line 386, in _test_connection
    return engine.connect()
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3204, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3283, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 311, in __init__
    self.encoding = charset_by_name(self.charset).encoding
AttributeError: 'NoneType' object has no attribute 'encoding'


```
from pip freeze

SQLAlchemy==1.4.28
sqlalchemy-migrate==0.13.0
SQLAlchemy-Utils==0.37.9
oslo.db==11.1.0
debtcollector==2.3.0

**Comment by mrunge** [comment]
This may have been my environment, trying to reproduce the issue failed.

**Comment by tobias-urdin** [comment]
Feel free to reopen if this is still relevant.
