### ISSUE TITLE
gnocchi doc gen on verge of failing

### ISSUE THREAD

**Issue by chungg** [gnocchixyz/gnocchi#154]
i'm pretty sure gnocchi.xyz docs job will fail soon. looking at logs, you can see it's using master libraries to build stable docs. if any of our libs break api, it will break gnocchi docs build regardless if we fix it in master.

ie. the logs will show lz4 warnings and pbr error on stable/*

> [36m=> Building ref: stable/3.1[39m
Running Sphinx v1.5.6
making output directory...
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/tester/src/.tox/docs-gnocchi.xyz/local/lib/python2.7/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/tester/src/.tox/docs-gnocchi.xyz/local/lib/python2.7/site-packages/pbr/util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/tester/src/.tox/docs-gnocchi.xyz/local/lib/python2.7/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/tester/src/.tox/docs-gnocchi.xyz/local/lib/python2.7/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/tester/src/.tox/docs-gnocchi.xyz/local/lib/python2.7/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/home/tester/src/.tox/docs-gnocchi.xyz/local/lib/python2.7/site-packages/pbr/packaging.py", line 755, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name gnocchi was given, but was not able to be found.
error in setup command: Error parsing /tmp/tmpr2_VHesphinxcontrib_versioning/22b7d4e4a2de2de77ad26795a9de8bf241e07293/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name gnocchi was given, but was not able to be found.
2017-06-27 19:25:09.297 1457 WARNING oslo_db.sqlalchemy.engines [-] URL postgresql://localhost/postgres?host=/tmp/tmpUB6_PY&port=9824 does not contain a '+drivername' portion, and will make use of a default driver.  A full dbname+drivername:// protocol is recommended.
2017-06-27 19:25:09.308 1457 INFO alembic.runtime.migration [-] Context impl PostgresqlImpl.
2017-06-27 19:25:09.308 1457 INFO alembic.runtime.migration [-] Will assume transactional DDL.
2017-06-27 19:25:09.371 1457 WARNING oslo_db.sqlalchemy.engines [-] URL postgresql://localhost/postgres?host=/tmp/tmpUB6_PY&port=9824 does not contain a '+drivername' portion, and will make use of a default driver.  A full dbname+drivername:// protocol is recommended.
2017-06-27 19:25:09.380 1457 INFO alembic.runtime.migration [-] Context impl PostgresqlImpl.
2017-06-27 19:25:09.380 1457 INFO alembic.runtime.migration [-] Will assume transactional DDL.
2017-06-27 19:25:09.396 1457 INFO alembic.runtime.migration [-] Running stamp_revision  -> 1e1a63d3d186
2017-06-27 19:25:09.437 1457 INFO gnocchi.rest.app [-] WSGI config used: /tmp/tmpr2_VHesphinxcontrib_versioning/22b7d4e4a2de2de77ad26795a9de8bf241e07293/gnocchi/rest/api-paste.ini
/home/tester/src/.tox/docs-gnocchi.xyz/local/lib/python2.7/site-packages/lz4/__init__.py:30: DeprecationWarning: Call to deprecated function or method dumps (use lz4.block.compress instead).
  def dumps(source):
/home/tester/src/.tox/docs-gnocchi.xyz/local/lib/python2.7/site-packages/lz4/__init__.py:30: DeprecationWarning: Call to deprecated function or method dumps (use lz4.block.compress instead).
  def dumps(source):
/home/tester/src/.tox/docs-gnocchi.xyz/local/lib/python2.7/site-packages/lz4/__init__.py:30: DeprecationWarning: Call to deprecated function or method dumps (use lz4.block.compress instead).
  def dumps(source):
/home/tester/src/.tox/docs-gnocchi.xyz/local/lib/python2.7/site-packages/lz4/__init__.py:30: DeprecationWarning: Call to deprecated function or method dumps (use lz4.block.compress instead).
  def dumps(source):
/home/tester/src/.tox/docs-gnocchi.xyz/local/lib/python2.7/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/tester/src/.tox/docs-gnocchi.xyz/local/lib/python2.7/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in double_scalars

**Comment by jd** [comment]
Yeah so far we have manually updated the deps list in tox.ini `[docs-gnocchi.xyz]` target. I don't know if we can do anything better right now. As soon as 2 versions of Gnocchi will have 2 incompatible requirements, we will have to stop building the older version I guess. :(
Since everything is built in the same venv, it is pretty fragile obviously. The main issue is probably that we run code with `gendoc` to build the doc. That works fine for current version, but mixing that with old version at the same time is very fragile.

**Comment by jd** [comment]
We now have a job that fails if the doc cannot be built, thanks to @sileht.
