### ISSUE TITLE
Unable to install from tarball

### ISSUE THREAD

**Issue by egonzalez90** [gnocchixyz/gnocchi#157]
While trying to install gnocchi from tarball build in github https://github.com/gnocchixyz/gnocchi/archive/master.tar.gz

Gives pbr errors:

```
INFO:kolla.image.build.gnocchi-base:Processing /gnocchi
INFO:kolla.image.build.gnocchi-base:    Complete output from command python setup.py egg_info:
INFO:kolla.image.build.gnocchi-base:    ERROR:root:Error parsing
INFO:kolla.image.build.gnocchi-base:    Traceback (most recent call last):
INFO:kolla.image.build.gnocchi-base:      File "/var/lib/kolla/venv/lib/python2.7/site-packages/pbr/core.py", line 111, in pbr
INFO:kolla.image.build.gnocchi-base:        attrs = util.cfg_to_args(path, dist.script_args)
INFO:kolla.image.build.gnocchi-base:      File "/var/lib/kolla/venv/lib/python2.7/site-packages/pbr/util.py", line 249, in cfg_to_args
INFO:kolla.image.build.gnocchi-base:        pbr.hooks.setup_hook(config)
INFO:kolla.image.build.gnocchi-base:      File "/var/lib/kolla/venv/lib/python2.7/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
INFO:kolla.image.build.gnocchi-base:        metadata_config.run()
INFO:kolla.image.build.gnocchi-base:      File "/var/lib/kolla/venv/lib/python2.7/site-packages/pbr/hooks/base.py", line 27, in run
INFO:kolla.image.build.gnocchi-base:        self.hook()
INFO:kolla.image.build.gnocchi-base:      File "/var/lib/kolla/venv/lib/python2.7/site-packages/pbr/hooks/metadata.py", line 26, in hook
INFO:kolla.image.build.gnocchi-base:        self.config['name'], self.config.get('version', None))
INFO:kolla.image.build.gnocchi-base:      File "/var/lib/kolla/venv/lib/python2.7/site-packages/pbr/packaging.py", line 755, in get_version
INFO:kolla.image.build.gnocchi-base:        name=package_name))
INFO:kolla.image.build.gnocchi-base:    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name gnocchi was given, but was not able to be found.
INFO:kolla.image.build.gnocchi-base:    error in setup command: Error parsing /tmp/pip-QCtHsN-build/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name gnocchi was given, but was not able to be found.
```

Executing pbr versioning inside downloaded tarball gives same error.
`python -c "import pbr.version; print(pbr.version.VersionInfo('gnocchi'))"`

**Comment by jd** [comment]
The error message says it all, you can't install via a tarball. You need to build a sdist tarball or install from git. Or use the sdist from PyPI.
