### ISSUE TITLE
TypeError: 'Retrying' object is not callable

### ISSUE THREAD

**Issue by skinnyh** [gnocchixyz/gnocchi#218]
gnocchi-metricd is not working in devstack-stable/ocata

In gnocchi-metricd .log:

2017-07-20 05:04:06,805 [25546] ^[[01;31mERROR    cotyledon._utils: Unhandled exception^[[0m
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cotyledon/_utils.py", line 95, in exit_on_exception
    yield
  File "/usr/lib/python2.7/site-packages/cotyledon/_service.py", line 139, in _run
    self.run()
  File "/opt/stack/gnocchi/gnocchi/cli.py", line 131, in run
    self._configure()
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 87, in wrapped_f
    return r.call(f, *args, **kw)
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 235, in call
    do = self.iter(result=result, exc_info=exc_info)
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 194, in iter
    return fut.result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python2.7/site-packages/tenacity/__init__.py", line 238, in call
    result = fn(*args, **kwargs)
  File "/opt/stack/gnocchi/gnocchi/cli.py", line 198, in _configure
    self.conf.storage.coordination_url)
TypeError: 'Retrying' object is not callable

Is this related about this recent commit?
https://github.com/gnocchixyz/gnocchi/commit/112bf6242a953e008df26d1ab946ae50fed7333b

I'm using tenacity==3.7.1 which is pinned in requirements/upper-constraints.txt

**Comment by sileht** [comment]
Looks like we require 4.0.0
