### ISSUE TITLE
Fail to run Gnocchi

### ISSUE THREAD

**Issue by accjiyun** [gnocchixyz/gnocchi#226]
when I run gnocchi commands, it is failing.
```
[root@controller1 ~]# gnocchi-api
Traceback (most recent call last):
  File "/usr/bin/gnocchi-api", line 6, in <module>
    from gnocchi.rest.app import build_wsgi_app
  File "/usr/lib/python2.7/site-packages/gnocchi/rest/__init__.py", line 39, in <module>
    from gnocchi import resource_type
  File "/usr/lib/python2.7/site-packages/gnocchi/resource_type.py", line 21, in <module>
    from gnocchi import utils
  File "/usr/lib/python2.7/site-packages/gnocchi/utils.py", line 28, in <module>
    import pandas as pd
  File "/usr/lib64/python2.7/site-packages/pandas/__init__.py", line 39, in <module>
    from pandas.core.api import *
  File "/usr/lib64/python2.7/site-packages/pandas/core/api.py", line 20, in <module>
    from pandas.core.reshape import (pivot_simple as pivot, get_dummies,
ImportError: cannot import name pivot_simple
[root@controller1 ~]# gnocchi-metricd
Traceback (most recent call last):
  File "/usr/bin/gnocchi-metricd", line 6, in <module>
    from gnocchi.cli import metricd
  File "/usr/lib/python2.7/site-packages/gnocchi/cli.py", line 36, in <module>
    from gnocchi import service
  File "/usr/lib/python2.7/site-packages/gnocchi/service.py", line 27, in <module>
    from gnocchi import opts
  File "/usr/lib/python2.7/site-packages/gnocchi/opts.py", line 27, in <module>
    import gnocchi.storage.ceph
  File "/usr/lib/python2.7/site-packages/gnocchi/storage/ceph.py", line 22, in <module>
    from gnocchi.storage import _carbonara
  File "/usr/lib/python2.7/site-packages/gnocchi/storage/_carbonara.py", line 33, in <module>
    from gnocchi import carbonara
  File "/usr/lib/python2.7/site-packages/gnocchi/carbonara.py", line 32, in <module>
    import pandas
  File "/usr/lib64/python2.7/site-packages/pandas/__init__.py", line 39, in <module>
    from pandas.core.api import *
  File "/usr/lib64/python2.7/site-packages/pandas/core/api.py", line 20, in <module>
    from pandas.core.reshape import (pivot_simple as pivot, get_dummies,
ImportError: cannot import name pivot_simple
[root@controller1 ~]# gnocchi resource list  --type image
Unable to establish connection to http://localhost:8041/v1/resource/image?: HTTPConnectionPool(host='localhost', port=8041): Max retries exceeded with url: /v1/resource/image (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x281be10>: Failed to establish a new connection: [Errno 111] \xe6\x8b\x92\xe7\xbb\x9d\xe8\xbf\x9e\xe6\x8e\xa5',))
```

Gnocchi services' status below:
```
[root@controller1 ~]# systemctl status openstack-gnocchi-api.service openstack-gnocchi-metricd.service openstack-gnocchi-statsd.service
● openstack-gnocchi-api.service - OpenStack ceilometer API service
   Loaded: loaded (/usr/lib/systemd/system/openstack-gnocchi-api.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 五 2017-07-21 15:29:37 CST; 2h 17min ago
 Main PID: 18914 (code=exited, status=1/FAILURE)

7月 21 15:29:37 controller1 systemd[1]: Unit openstack-gnocchi-api.service entered failed state.
7月 21 15:29:37 controller1 systemd[1]: openstack-gnocchi-api.service failed.
7月 21 15:29:37 controller1 systemd[1]: openstack-gnocchi-api.service holdoff time over, scheduling restart.
7月 21 15:29:37 controller1 systemd[1]: start request repeated too quickly for openstack-gnocchi-api.service
7月 21 15:29:37 controller1 systemd[1]: Failed to start OpenStack ceilometer API service.
7月 21 15:29:37 controller1 systemd[1]: Unit openstack-gnocchi-api.service entered failed state.
7月 21 15:29:37 controller1 systemd[1]: openstack-gnocchi-api.service failed.

● openstack-gnocchi-metricd.service - OpenStack gnocchi metricd service
   Loaded: loaded (/usr/lib/systemd/system/openstack-gnocchi-metricd.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 五 2017-07-21 14:07:47 CST; 3h 39min ago
 Main PID: 3707 (code=exited, status=1/FAILURE)

7月 21 14:07:47 controller1 systemd[1]: Unit openstack-gnocchi-metricd.service entered failed state.
7月 21 14:07:47 controller1 systemd[1]: openstack-gnocchi-metricd.service failed.
7月 21 14:07:47 controller1 systemd[1]: openstack-gnocchi-metricd.service holdoff time over, scheduling restart.
7月 21 14:07:47 controller1 systemd[1]: start request repeated too quickly for openstack-gnocchi-metricd.service
7月 21 14:07:47 controller1 systemd[1]: Failed to start OpenStack gnocchi metricd service.
7月 21 14:07:47 controller1 systemd[1]: Unit openstack-gnocchi-metricd.service entered failed state.
7月 21 14:07:47 controller1 systemd[1]: openstack-gnocchi-metricd.service failed.

● openstack-gnocchi-statsd.service - OpenStack gnocchi statsd service
   Loaded: loaded (/usr/lib/systemd/system/openstack-gnocchi-statsd.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since 五 2017-07-21 14:07:47 CST; 3h 39min ago
 Main PID: 3713 (code=exited, status=1/FAILURE)

7月 21 14:07:47 controller1 systemd[1]: Unit openstack-gnocchi-statsd.service entered failed state.
7月 21 14:07:47 controller1 systemd[1]: openstack-gnocchi-statsd.service failed.
7月 21 14:07:47 controller1 systemd[1]: openstack-gnocchi-statsd.service holdoff time over, scheduling restart.
7月 21 14:07:47 controller1 systemd[1]: start request repeated too quickly for openstack-gnocchi-statsd.service
7月 21 14:07:47 controller1 systemd[1]: Failed to start OpenStack gnocchi statsd service.
7月 21 14:07:47 controller1 systemd[1]: Unit openstack-gnocchi-statsd.service entered failed state.
7月 21 14:07:47 controller1 systemd[1]: openstack-gnocchi-statsd.service failed.
```

**Comment by sileht** [comment]
That looks unrelated with Gnocchi. But an issue with your pandas python module.

You can confirm with: `python -c "import pandas"`

**Comment by accjiyun** [comment]
@sileht Yes, you are right!
```
[root@controller1 ~]# python -c "import pandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/pandas/__init__.py", line 39, in <module>
    from pandas.core.api import *
  File "/usr/lib64/python2.7/site-packages/pandas/core/api.py", line 20, in <module>
    from pandas.core.reshape import (pivot_simple as pivot, get_dummies,
ImportError: cannot import name pivot_simple
```
But it was installed.
so, how could i do?
```
[root@controller1 ~]# pip install pandas
Requirement already satisfied: pandas in /usr/lib64/python2.7/site-packages
Requirement already satisfied: numpy>=1.7.0 in /usr/lib64/python2.7/site-packages (from pandas)
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/site-packages (from pandas)
Requirement already satisfied: pytz>=2011k in /usr/lib/python2.7/site-packages (from pandas)
Requirement already satisfied: six>=1.5 in /usr/lib/python2.7/site-packages (from python-dateutil->pandas)
```

**Comment by sileht** [comment]
You should open a bug on your linux distro.

**Comment by accjiyun** [comment]
It sounds so a bit sad.

**Comment by accjiyun** [comment]
I change my pandas and other python module's version, it works.
pandas use 0.18.0.
