### ISSUE TITLE
releases in github page is not installable.

### ISSUE THREAD

**Issue by jeffrey4l** [gnocchixyz/gnocchi#282]
```
# pip install -U  https://github.com/gnocchixyz/gnocchi/archive/4.0.2.tar.gz\#egg\=gnocchi                                                                                           
Collecting gnocchi from https://github.com/gnocchixyz/gnocchi/archive/4.0.2.tar.gz#egg=gnocchi
  Downloading https://github.com/gnocchixyz/gnocchi/archive/4.0.2.tar.gz (870kB)
    100% |████████████████████████████████| 870kB 873kB/s 
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d1HoE1/gnocchi/
```

```
# wget -c https://github.com/gnocchixyz/gnocchi/archive/4.0.2.tar.gz
# tar xvf 4.0.2.tar.gz
# cd gnocchi-4.0.2
# python setup.py install
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/jeffrey/.dotfiles/virtualenvs/test/lib/python2.7/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/jeffrey/.dotfiles/virtualenvs/test/lib/python2.7/site-packages/pbr/util.py", line 246, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/jeffrey/.dotfiles/virtualenvs/test/lib/python2.7/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/jeffrey/.dotfiles/virtualenvs/test/lib/python2.7/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/jeffrey/.dotfiles/virtualenvs/test/lib/python2.7/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/home/jeffrey/.dotfiles/virtualenvs/test/lib/python2.7/site-packages/pbr/packaging.py", line 725, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
error in setup command: Error parsing /home/jeffrey/temp/gnocchi-4.0.2/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?

```

The issue is that gnocchi is using pbr, which load the version from gnocchi.egg-info file or git info. whereas github release is just tar zip file.

**Comment by jd** [comment]
We release on PyPI so there's no need to use tarballs from GitHub.
