### ISSUE TITLE
ValueError: Little-endian buffer not supported on big-endian compiler

### ISSUE THREAD

**Issue by ziontrain** [gnocchixyz/gnocchi#285]
When adding a new resource with metrics everything works but when adding new measurements for any of the metrics it fails.

Gnocchi version: **stable/4.0**
Arch: **s390x**

I have seen other having the same problem with pandas and it seems like a conversion is needed.

**Adding a new resource with metrics**
2017-08-21 16:20:22,948 [11529] DEBUG    gnocchi.storage._carbonara: Processing measures for fd616c1d-7401-4187-9ea6-08eb5702a9a1
2017-08-21 16:20:22,959 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (count) for metric fd616c1d-7401-4187-9ea6-08eb5702a9a1
2017-08-21 16:20:22,962 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (min) for metric fd616c1d-7401-4187-9ea6-08eb5702a9a1
2017-08-21 16:20:22,964 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (max) for metric fd616c1d-7401-4187-9ea6-08eb5702a9a1
2017-08-21 16:20:22,965 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (sum) for metric fd616c1d-7401-4187-9ea6-08eb5702a9a1
2017-08-21 16:20:22,966 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (mean) for metric fd616c1d-7401-4187-9ea6-08eb5702a9a1
2017-08-21 16:20:22,967 [11529] DEBUG    gnocchi.storage._carbonara: Computed new metric fd616c1d-7401-4187-9ea6-08eb5702a9a1 with 1 new measures in 0.02 seconds (395 points/s, 395 measures/s)
2017-08-21 16:20:22,968 [11529] DEBUG    gnocchi.storage._carbonara: Measures for metric fd616c1d-7401-4187-9ea6-08eb5702a9a1 processed
2017-08-21 16:20:22,975 [11529] DEBUG    gnocchi.storage._carbonara: Processing measures for aa9e285d-808d-46d0-809a-ee94304337ad
2017-08-21 16:20:22,980 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (count) for metric aa9e285d-808d-46d0-809a-ee94304337ad
2017-08-21 16:20:22,982 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (min) for metric aa9e285d-808d-46d0-809a-ee94304337ad
2017-08-21 16:20:22,983 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (max) for metric aa9e285d-808d-46d0-809a-ee94304337ad
2017-08-21 16:20:22,985 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (sum) for metric aa9e285d-808d-46d0-809a-ee94304337ad
2017-08-21 16:20:22,986 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (mean) for metric aa9e285d-808d-46d0-809a-ee94304337ad
2017-08-21 16:20:22,987 [11529] DEBUG    gnocchi.storage._carbonara: Computed new metric aa9e285d-808d-46d0-809a-ee94304337ad with 1 new measures in 0.01 seconds (578 points/s, 578 measures/s)
2017-08-21 16:20:22,987 [11529] DEBUG    gnocchi.storage._carbonara: Measures for metric aa9e285d-808d-46d0-809a-ee94304337ad processed
2017-08-21 16:20:22,994 [11529] DEBUG    gnocchi.storage._carbonara: Processing measures for 79b88cd4-71cc-4838-87d5-ad28b9a0f240
2017-08-21 16:20:22,998 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (count) for metric 79b88cd4-71cc-4838-87d5-ad28b9a0f240
2017-08-21 16:20:22,999 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (min) for metric 79b88cd4-71cc-4838-87d5-ad28b9a0f240
2017-08-21 16:20:23,001 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (max) for metric 79b88cd4-71cc-4838-87d5-ad28b9a0f240
2017-08-21 16:20:23,002 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (sum) for metric 79b88cd4-71cc-4838-87d5-ad28b9a0f240
2017-08-21 16:20:23,003 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (mean) for metric 79b88cd4-71cc-4838-87d5-ad28b9a0f240
2017-08-21 16:20:23,003 [11529] DEBUG    gnocchi.storage._carbonara: Computed new metric 79b88cd4-71cc-4838-87d5-ad28b9a0f240 with 1 new measures in 0.01 seconds (738 points/s, 738 measures/s)
2017-08-21 16:20:23,004 [11529] DEBUG    gnocchi.storage._carbonara: Measures for metric 79b88cd4-71cc-4838-87d5-ad28b9a0f240 processed
2017-08-21 16:20:23,014 [11529] DEBUG    gnocchi.storage._carbonara: Processing measures for df38471b-4fe7-43ff-a78d-d8ef61bbd870
2017-08-21 16:20:23,018 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (count) for metric df38471b-4fe7-43ff-a78d-d8ef61bbd870
2017-08-21 16:20:23,019 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (min) for metric df38471b-4fe7-43ff-a78d-d8ef61bbd870
2017-08-21 16:20:23,020 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (max) for metric df38471b-4fe7-43ff-a78d-d8ef61bbd870
2017-08-21 16:20:23,021 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (sum) for metric df38471b-4fe7-43ff-a78d-d8ef61bbd870
2017-08-21 16:20:23,022 [11529] DEBUG    gnocchi.storage._carbonara: Storing split 1502280000.0 (mean) for metric df38471b-4fe7-43ff-a78d-d8ef61bbd870
2017-08-21 16:20:23,023 [11529] DEBUG    gnocchi.storage._carbonara: Computed new metric df38471b-4fe7-43ff-a78d-d8ef61bbd870 with 1 new measures in 0.01 seconds (751 points/s, 751 measures/s)
2017-08-21 16:20:23,024 [11529] DEBUG    gnocchi.storage._carbonara: Measures for metric df38471b-4fe7-43ff-a78d-d8ef61bbd870 processed
2017-08-21 16:20:23,026 [11529] DEBUG    gnocchi.cli: 4 metrics processed from 128 sacks
2017-08-21 16:21:21,533 [11530] INFO     gnocchi.cli: 0 measurements bundles across 0 metrics wait to be processed.
2017-08-21 16:21:22,921 [11529] DEBUG    gnocchi.cli: 0 metrics processed from 128 sacks

**Adding measurements to metric in the above created resource**
2017-08-21 16:22:22,918 [11529] DEBUG    gnocchi.storage._carbonara: Processing measures for aa9e285d-808d-46d0-809a-ee94304337ad
2017-08-21 16:22:22,918 [11529] DEBUG    gnocchi.storage._carbonara: Retrieve unaggregated measures for aa9e285d-808d-46d0-809a-ee94304337ad in 0.00s
2017-08-21 16:22:22,920 [11529] ERROR    gnocchi.storage._carbonara: Error processing new measures
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gnocchi/storage/_carbonara.py", line 383, in process_new_measures
    self._compute_and_store_timeseries(metric, measures)
  File "/usr/lib/python2.7/site-packages/gnocchi/storage/_carbonara.py", line 454, in _compute_and_store_timeseries
    before_truncate_callback=_map_add_measures)
  File "/usr/lib/python2.7/site-packages/gnocchi/carbonara.py", line 284, in set_values
    super(BoundTimeSerie, self).set_values(values)
  File "/usr/lib/python2.7/site-packages/gnocchi/carbonara.py", line 198, in set_values
    self.ts = self.clean_ts(t).combine_first(self.ts)
  File "/usr/lib64/python2.7/site-packages/pandas-0.20.3-py2.7-linux-s390x.egg/pandas/core/series.py", line 1656, in combine_first
    other = other.reindex(new_index, copy=False)
  File "/usr/lib64/python2.7/site-packages/pandas-0.20.3-py2.7-linux-s390x.egg/pandas/core/series.py", line 2426, in reindex
    return super(Series, self).reindex(index=index, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pandas-0.20.3-py2.7-linux-s390x.egg/pandas/core/generic.py", line 2515, in reindex
    fill_value, copy).__finalize__(self)
  File "/usr/lib64/python2.7/site-packages/pandas-0.20.3-py2.7-linux-s390x.egg/pandas/core/generic.py", line 2533, in _reindex_axes
    copy=copy, allow_dups=False)
  File "/usr/lib64/python2.7/site-packages/pandas-0.20.3-py2.7-linux-s390x.egg/pandas/core/generic.py", line 2627, in _reindex_with_indexers
    copy=copy)
  File "/usr/lib64/python2.7/site-packages/pandas-0.20.3-py2.7-linux-s390x.egg/pandas/core/internals.py", line 3893, in reindex_indexer
    fill_tuple=(fill_value,))
  File "/usr/lib64/python2.7/site-packages/pandas-0.20.3-py2.7-linux-s390x.egg/pandas/core/internals.py", line 3932, in _slice_take_blocks_ax0
    fill_tuple=fill_tuple)]
  File "/usr/lib64/python2.7/site-packages/pandas-0.20.3-py2.7-linux-s390x.egg/pandas/core/internals.py", line 1046, in take_nd
    allow_fill=True, fill_value=fill_value)
  File "/usr/lib64/python2.7/site-packages/pandas-0.20.3-py2.7-linux-s390x.egg/pandas/core/algorithms.py", line 1471, in take_nd
    func(arr, indexer, out, fill_value)
  File "pandas/_libs/algos_take_helper.pxi", line 4463, in pandas._libs.algos.take_1d_float64_float64 (pandas/_libs/algos.c:109616)
**ValueError: Little-endian buffer not supported on big-endian compiler**

**Comment by jd** [comment]
Could you give it a try with master?

**Comment by ziontrain** [comment]
Works like a charm! Thanks!

**Comment by jd** [comment]
Awesome. I'll close this but it'll affect any version <=4.0.
I guess the rewrite of the code using Numpy rather than Pandas in many area solved that, so that's cool.
