### ISSUE TITLE
Commit c8717e8b7 makes oslo-config-generator fail

### ISSUE THREAD

**Issue by zaitcev** [gnocchixyz/gnocchi#294]
Problem looks like this, you try to build an RPM with current trunk and:

```
+ PYTHONPATH=.
+ oslo-config-generator --config-file=gnocchi/gnocchi-config-generator.conf --output-file=gnocchi/gnocchi.conf
Traceback (most recent call last):
  File "/usr/bin/oslo-config-generator", line 10, in <module>
    sys.exit(main())
............
  File "/usr/lib/python2.7/site-packages/stevedore/extension.py", line 191, in _load_one_plugin
    plugin = ep.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/rpms/BUILD/gnocchi-4.0.0.z2/gnocchi/opts.py", line 25, in <module>
    import gnocchi.rest.app
  File "/root/rpms/BUILD/gnocchi-4.0.0.z2/gnocchi/rest/app.py", line 34, in <module>
    from gnocchi import service
  File "/root/rpms/BUILD/gnocchi-4.0.0.z2/gnocchi/service.py", line 28, in <module>
    from gnocchi import opts
ImportError: cannot import name opts
```

Obviously, a recursive import.

Not sure what to do about this. The spec explicitly does this:

```
# Generate config file
PYTHONPATH=. oslo-config-generator --config-file=gnocchi/gnocchi-config-generator.conf --output-file=gnocchi/gnocchi.conf
%{__python2} setup.py build
```

I don't know if that's how you do it in Oslo, is this even legitimate.

On the other hand, clearly a recursive import, Oslo or no Oslo.

**Comment by jd** [comment]
Interesting, the circular dependency exists in `master` but does not raise any error. Neither on my system on `stable/4.0`.
