### ISSUE TITLE
os error while running gnocchi-api

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [gnocchixyz/gnocchi#313]
after configuring gnocchi, I tried gnocchi-api but i am getting this error, can someone help me. I am using google cloud compute engine with debain linux.

CRITICAL root: Traceback (most recent call last):
  File "/usr/local/bin/gnocchi-api", line 37, in <module>
    server = wss.make_server(args.host, args.port, build_wsgi_app())
  File "/usr/local/lib/python2.7/dist-packages/gnocchi/rest/app.py", line 143, in build_wsgi_app
    return load_app(service.prepare_service())
  File "/usr/local/lib/python2.7/dist-packages/gnocchi/rest/app.py", line 92, in load_app
    storage = gnocchi_storage.get_driver(conf)
  File "/usr/local/lib/python2.7/dist-packages/gnocchi/storage/__init__.py", line 163, in get_driver
    conf.storage, incoming, coord)
  File "/usr/local/lib/python2.7/dist-packages/gnocchi/storage/file.py", line 43, in __init__
    utils.ensure_paths([self.basepath_tmp])
  File "/usr/local/lib/python2.7/dist-packages/gnocchi/utils.py", line 197, in ensure_paths
    os.makedirs(p)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/var/lib/gnocchi'

**Comment by sileht** [comment]
It have nothing to do with Gnocchi. You have set some path in your gnocchi.conf that point to a location that your current user is not permitted to write...

Please read the documentation: http://gnocchi.xyz

**Comment by ramesh-chowdeshetty** [comment]
May i know how to bind gnocchi-api to 0.0.0.0 , so that i can access server in my local system

**Comment by chungg** [comment]
closing this, since you created another issue for the second question
