### ISSUE TITLE
gnocchi 4.0.3 not compatible with python-rados >= 10.1.0

### ISSUE THREAD

**Issue by javacruft** [gnocchixyz/gnocchi#412]
Before reporting an issue on Gnocchi, please be sure to provide all necessary
information.

### Which version of Gnocchi are you using

4.0.3 with python-rados from Ubuntu Xenial (currently 10.2.7)

This should full-fill the documented requirement for 10.1.0 of this python module

### How to reproduce your problem

Deploy gnocchi with ceph storage backend; start collecting measures - add_measures_batch fails due to missing 'operate_aio_write_op' method in python-rados bindings @10.2.7

### What is the result that you get

```
2017-10-05 10:10:29,927 [6341] CRITICAL root: Traceback (most recent call last):
  File "/snap/gnocchi/14/lib/python2.7/site-packages/webob/dec.py", line 131, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/webob/dec.py", line 196, in call_func
    return self.func(req, *args, **kwargs)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/oslo_middleware/base.py", line 131, in __call__
    response = req.get_response(self.application)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/webob/request.py", line 1316, in send
    application, catch_exc_info=False)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/webob/request.py", line 1280, in call_application
    app_iter = application(self.environ, start_response)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/paste/urlmap.py", line 216, in __call__
    return app(environ, start_response)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/webob/dec.py", line 131, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/webob/dec.py", line 196, in call_func
    return self.func(req, *args, **kwargs)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/oslo_middleware/base.py", line 131, in __call__
    response = req.get_response(self.application)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/webob/request.py", line 1316, in send
    application, catch_exc_info=False)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/webob/request.py", line 1280, in call_application
    app_iter = application(self.environ, start_response)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/webob/dec.py", line 131, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/webob/dec.py", line 196, in call_func
    return self.func(req, *args, **kwargs)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/keystonemiddleware/auth_token/__init__.py", line 334, in __call__
    response = req.get_response(self._app)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/webob/request.py", line 1316, in send
    application, catch_exc_info=False)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/webob/request.py", line 1280, in call_application
    app_iter = application(self.environ, start_response)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/webob/exc.py", line 1162, in __call__
    return self.application(environ, start_response)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/gnocchi/rest/app.py", line 69, in __call__
    return self.app(environ, start_response)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/pecan/middleware/recursive.py", line 56, in __call__
    return self.application(environ, start_response)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/pecan/core.py", line 840, in __call__
    return super(Pecan, self).__call__(environ, start_response)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/pecan/core.py", line 683, in __call__
    self.invoke_controller(controller, args, kwargs, state)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/pecan/core.py", line 574, in invoke_controller
    result = controller(*args, **kwargs)
  File "/snap/gnocchi/14/lib/python2.7/site-packages/gnocchi/rest/__init__.py", line 1477, in post
    for metric in known_metrics))
  File "/snap/gnocchi/14/lib/python2.7/site-packages/gnocchi/storage/incoming/ceph.py", line 103, in add_measures_batch
    ops.append(self.ioctx.operate_aio_write_op(
AttributeError: 'rados.Ioctx' object has no attribute 'operate_aio_write_op'
```
### What is result that you expected

Functional measures!

**Comment by javacruft** [comment]
FWIW the fix here might be to just update the minimum python-rados requirement to >= 12.2.0

**Comment by sileht** [comment]
Or switch to python-cradox. python-cradox exists especially to provide up2date python binding on old ceph version.

**Comment by javacruft** [comment]
@sileht do you happen to know which ceph versions cradox supports?  10.2.7 and 10.2.9 are def not happy

**Comment by sileht** [comment]
On Thu, Oct 05, 2017 at 06:17:07AM -0700, James Page wrote:
>@sileht do you happen to know which ceph versions cradox supports?  10.2.7 and 10.2.9 are def not happy

In theorie, rados_aio_write_op_operate is avialable on C side since 0.80. so 10.2.7 or 10.2.9 should work well.
cradox must be >= 1.2.0

-- 
Mehdi Abaakouk
mail: sileht@sileht.net
irc: sileht

**Comment by yjLiInSky** [comment]
i  switch to python-cradox. An error occurred: `ImportError: No module named api`.
what is the reason?

**Comment by jd** [comment]
probably an mix of different installed version. clean your env.
