### ISSUE TITLE
Import Pandas Error with Gnocchi installation with devstack

### ISSUE THREAD

**Issue by maestropandy** [gnocchixyz/gnocchi#483]
Can able to install devstack/ocata with Aodh, panko, ceilometer, heat. where while installing gnocchi, getting error 

> the C extensions first.".format(module))
ImportError: C extension: umpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

Note: Normal installation of pandas, numpy don't have any issue, where doing with gnocchi plugin with devstack getting issue.

For test case: I have installed numpy (first) and pandas and tried import, it was successful. But if I add gnocchi plugin with devstack, throwing error in same machine. where import numpy is working ( which doesn't need for gnocchi), importing pandas getting error 

Here completer error 

2017-11-14 11:02:48.738 | ++lib/keystone:configure_auth_token_middleware:483  local section=keystone_authtoken
2017-11-14 11:02:48.746 | ++lib/keystone:configure_auth_token_middleware:485  iniset /etc/gnocchi/gnocchi.conf keystone_authtoken auth_type password
2017-11-14 11:02:48.825 | ++lib/keystone:configure_auth_token_middleware:486  iniset /etc/gnocchi/gnocchi.conf keystone_authtoken auth_url http://30.30.0.5/identity_admin
2017-11-14 11:02:48.910 | ++lib/keystone:configure_auth_token_middleware:487  iniset /etc/gnocchi/gnocchi.conf keystone_authtoken username gnocchi
2017-11-14 11:02:48.995 | ++lib/keystone:configure_auth_token_middleware:488  iniset /etc/gnocchi/gnocchi.conf keystone_authtoken password admin
2017-11-14 11:02:49.087 | ++lib/keystone:configure_auth_token_middleware:489  iniset /etc/gnocchi/gnocchi.conf keystone_authtoken user_domain_name Default
2017-11-14 11:02:49.167 | ++lib/keystone:configure_auth_token_middleware:490  iniset /etc/gnocchi/gnocchi.conf keystone_authtoken project_name service
2017-11-14 11:02:49.237 | ++lib/keystone:configure_auth_token_middleware:491  iniset /etc/gnocchi/gnocchi.conf keystone_authtoken project_domain_name Default
2017-11-14 11:02:49.324 | ++lib/keystone:configure_auth_token_middleware:493  iniset /etc/gnocchi/gnocchi.conf keystone_authtoken auth_uri http://30.30.0.5/identity
2017-11-14 11:02:49.404 | ++lib/keystone:configure_auth_token_middleware:494  iniset /etc/gnocchi/gnocchi.conf keystone_authtoken cafile /opt/stack/data/ca-bundle.pem
2017-11-14 11:02:49.467 | ++lib/keystone:configure_auth_token_middleware:495  iniset /etc/gnocchi/gnocchi.conf keystone_authtoken signing_dir /var/cache/gnocchi
2017-11-14 11:02:49.542 | ++lib/keystone:configure_auth_token_middleware:496  iniset /etc/gnocchi/gnocchi.conf keystone_authtoken memcached_servers 30.30.0.5:11211
2017-11-14 11:02:49.626 | ++/opt/stack/ceilometer/devstack/plugin.sh:install_gnocchi:221  sudo mkdir -p /var/cache/gnocchi
2017-11-14 11:02:49.650 | ++/opt/stack/ceilometer/devstack/plugin.sh:install_gnocchi:222  sudo chown ubuntu /var/cache/gnocchi
2017-11-14 11:02:49.674 | ++/opt/stack/ceilometer/devstack/plugin.sh:install_gnocchi:223  rm -f '/var/cache/gnocchi/*'
2017-11-14 11:02:49.688 | ++/opt/stack/ceilometer/devstack/plugin.sh:install_gnocchi:225  gnocchi-upgrade --create-legacy-resource-types
2017-11-14 11:02:50.357 | RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
2017-11-14 11:02:50.357 | Traceback (most recent call last):
2017-11-14 11:02:50.357 |   File "/usr/local/bin/gnocchi-upgrade", line 6, in <module>
2017-11-14 11:02:50.357 |     from gnocchi.cli import upgrade
2017-11-14 11:02:50.357 |   File "/opt/stack/gnocchi/gnocchi/cli.py", line 36, in <module>
2017-11-14 11:02:50.358 |     from gnocchi import service
2017-11-14 11:02:50.358 |   File "/opt/stack/gnocchi/gnocchi/service.py", line 27, in <module>
2017-11-14 11:02:50.358 |     from gnocchi import opts
2017-11-14 11:02:50.358 |   File "/opt/stack/gnocchi/gnocchi/opts.py", line 27, in <module>
2017-11-14 11:02:50.358 |     import gnocchi.storage.ceph
2017-11-14 11:02:50.358 |   File "/opt/stack/gnocchi/gnocchi/storage/ceph.py", line 22, in <module>
2017-11-14 11:02:50.358 |     from gnocchi.storage import _carbonara
2017-11-14 11:02:50.358 |   File "/opt/stack/gnocchi/gnocchi/storage/_carbonara.py", line 33, in <module>
2017-11-14 11:02:50.358 |     from gnocchi import carbonara
2017-11-14 11:02:50.358 |   File "/opt/stack/gnocchi/gnocchi/carbonara.py", line 32, in <module>
2017-11-14 11:02:50.358 |     import pandas
2017-11-14 11:02:50.358 |   File "/usr/local/lib/python2.7/dist-packages/pandas/__init__.py", line 35, in <module>
2017-11-14 11:02:50.359 |     "the C extensions first.".format(module))
2017-11-14 11:02:50.359 | ImportError: C extension: numpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
2017-11-14 11:02:50.400 | +/opt/stack/ceilometer/devstack/plugin.sh:install_gnocchi:1  exit_trap

**Comment by chungg** [comment]
pandas>=0.21.0 is not compatible with numpy<1.13.0. the reason this is a problem in devstack is because of openstack politics (this is my politically correct answer).

we have a workaround for these politics so this should hopefully fix it: https://review.openstack.org/#/c/519454/ hopefully have a release soon.

alternatively, just change the upper-constraint of numpy in your requirements directory.

**Comment by maestropandy** [comment]
I have installed latest pandas 0.21.0 & numpy 1.13.3 its working fine, thanks :)
