### ISSUE TITLE
sporadic test failure gabbi_live_live_get_myresource_measures_with_refresh

### ISSUE THREAD

**Issue by sileht** [gnocchixyz/gnocchi#529]
gabbi.suitemaker.test_gabbi_live_live_get_myresource_measures_with_refresh.test_request
---------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/home/tester/src/.tox/py27-postgresql/local/lib/python2.7/site-packages/gabbi/case.py", line 94, in wrapper
        func(self)
      File "/home/tester/src/.tox/py27-postgresql/local/lib/python2.7/site-packages/gabbi/case.py", line 143, in test_request
        self._run_test()
      File "/home/tester/src/.tox/py27-postgresql/local/lib/python2.7/site-packages/gabbi/case.py", line 534, in _run_test
        self._assert_response()
      File "/home/tester/src/.tox/py27-postgresql/local/lib/python2.7/site-packages/gabbi/case.py", line 191, in _assert_response
        handler(self)
      File "/home/tester/src/.tox/py27-postgresql/local/lib/python2.7/site-packages/gabbi/handlers/base.py", line 54, in __call__
        self.action(test, item, value=value)
      File "/home/tester/src/.tox/py27-postgresql/local/lib/python2.7/site-packages/gabbi/handlers/jsonhandler.py", line 112, in action
        (path, expected, match))
      File "/home/tester/src/.tox/py27-postgresql/local/lib/python2.7/site-packages/testtools/testcase.py", line 411, in assertEqual
        self.assertThat(observed, matcher, message)
      File "/home/tester/src/.tox/py27-postgresql/local/lib/python2.7/site-packages/testtools/testcase.py", line 498, in assertThat
        raise mismatch_error
    testtools.matchers._impl.MismatchError: 2 != 5.0: Unable to match $[3][2] as 2, got 5.0

**Comment by jd** [comment]
Did you see this recently @sileht? I did not.

**Comment by sileht** [comment]
Nop
