### ISSUE TITLE
PATCH resource type error 500

### ISSUE THREAD

**Issue by sileht** [gnocchixyz/gnocchi#616]
### Which version of Gnocchi are you using

-e git+https://github.com/gnocchixyz/gnocchi@cb2a4dfb1a1e2cab1a69d4f29b97a19ed4b280a0#egg=gnocchi

### How to reproduce your problem

Jan 08 14:13:39.860542 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]: [pid: 13869|app: 0|req: 24/48] 104.239.168.68 () {60 vars in 1263 bytes} [Mon Jan  8 14:13:39 2018] PATCH /metric/v1/resource_type/volume => generated 0 bytes in 49 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)

Jan 08 14:13:39.851908 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]: 2018-01-08 14:13:39,851 [13869] CRITICAL root: Traceback (most recent call last):
Jan 08 14:13:39.852200 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 131, in __call__
Jan 08 14:13:39.852413 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     resp = self.call_func(req, *args, **self.kwargs)
Jan 08 14:13:39.852641 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 196, in call_func
Jan 08 14:13:39.852844 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     return self.func(req, *args, **kwargs)
Jan 08 14:13:39.853045 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/oslo_middleware/base.py", line 131, in __call__
Jan 08 14:13:39.853245 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     response = req.get_response(self.application)
Jan 08 14:13:39.853440 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1327, in send
Jan 08 14:13:39.853645 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     application, catch_exc_info=False)
Jan 08 14:13:39.853840 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1291, in call_application
Jan 08 14:13:39.854037 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     app_iter = application(self.environ, start_response)
Jan 08 14:13:39.854243 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/paste/urlmap.py", line 216, in __call__
Jan 08 14:13:39.854439 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     return app(environ, start_response)
Jan 08 14:13:39.854633 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 131, in __call__
Jan 08 14:13:39.854862 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     resp = self.call_func(req, *args, **self.kwargs)
Jan 08 14:13:39.855053 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 196, in call_func
Jan 08 14:13:39.855179 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     return self.func(req, *args, **kwargs)
Jan 08 14:13:39.855316 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/oslo_middleware/base.py", line 131, in __call__
Jan 08 14:13:39.855440 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     response = req.get_response(self.application)
Jan 08 14:13:39.855561 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1327, in send
Jan 08 14:13:39.855681 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     application, catch_exc_info=False)
Jan 08 14:13:39.855800 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1291, in call_application
Jan 08 14:13:39.855923 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     app_iter = application(self.environ, start_response)
Jan 08 14:13:39.856044 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 131, in __call__
Jan 08 14:13:39.856164 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     resp = self.call_func(req, *args, **self.kwargs)
Jan 08 14:13:39.856284 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/webob/dec.py", line 196, in call_func
Jan 08 14:13:39.856407 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     return self.func(req, *args, **kwargs)
Jan 08 14:13:39.856530 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/keystonemiddleware/auth_token/__init__.py", line 337, in __call__
Jan 08 14:13:39.856659 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     response = req.get_response(self._app)
Jan 08 14:13:39.856800 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1327, in send
Jan 08 14:13:39.856921 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     application, catch_exc_info=False)
Jan 08 14:13:39.857041 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/webob/request.py", line 1291, in call_application
Jan 08 14:13:39.857160 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     app_iter = application(self.environ, start_response)
Jan 08 14:13:39.857280 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/webob/exc.py", line 1162, in __call__
Jan 08 14:13:39.857414 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     return self.application(environ, start_response)
Jan 08 14:13:39.857538 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/opt/stack/new/devstack/src/gnocchi/gnocchi/rest/app.py", line 96, in __call__
Jan 08 14:13:39.857659 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     return self.app(environ, start_response)
Jan 08 14:13:39.857788 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/pecan/middleware/recursive.py", line 56, in __call__
Jan 08 14:13:39.857910 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     return self.application(environ, start_response)
Jan 08 14:13:39.858035 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 840, in __call__
Jan 08 14:13:39.858162 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     return super(Pecan, self).__call__(environ, start_response)
Jan 08 14:13:39.858284 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 683, in __call__
Jan 08 14:13:39.858404 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     self.invoke_controller(controller, args, kwargs, state)
Jan 08 14:13:39.858536 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 574, in invoke_controller
Jan 08 14:13:39.858678 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     result = controller(*args, **kwargs)
Jan 08 14:13:39.858907 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/opt/stack/new/devstack/src/gnocchi/gnocchi/rest/api.py", line 926, in patch
Jan 08 14:13:39.859072 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     del_attributes=del_attrs)
Jan 08 14:13:39.859207 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/opt/stack/new/devstack/src/gnocchi/gnocchi/indexer/sqlalchemy.py", line 412, in update_resource_type
Jan 08 14:13:39.859331 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     server_default=server_default))
Jan 08 14:13:39.859458 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 1234, in __init__
Jan 08 14:13:39.859610 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     args.append(DefaultClause(self.server_default))
Jan 08 14:13:39.859745 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 2413, in __init__
Jan 08 14:13:39.859873 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     TextClause), 'arg')
Jan 08 14:13:39.860030 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 1104, in assert_arg_type
Jan 08 14:13:39.860196 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]:     (name, ' or '.join("'%s'" % a for a in argtype), type(arg)))
Jan 08 14:13:39.860374 ubuntu-xenial-rax-iad-0001732328 devstack@gnocchi-api.service[13866]: ArgumentError: Argument 'arg' is expected to be one of type '<type 'basestring'>' or '<class 'sqlalchemy.sql.elements.ClauseElement'>' or '<class 'sqlalchemy.sql.elements.TextClause'>', got '<type 'bool'>'

**Comment by sileht** [comment]
The payload:

       {"op": "add", "path": "/attributes/image_id",
          "value": {"type": "uuid", "required": False}},
         {"op": "add", "path": "/attributes/server_id",
          "value": {"type": "uuid", "required": False}},
