### ISSUE TITLE
Problems with connecting to CEPH 12.2.2

### ISSUE THREAD

**Issue by gunph1ld** [gnocchixyz/gnocchi#657]
Hello, 
Got a critical error while connecting to the ceph cluster. 

### Which version of Gnocchi are you using
```
[root@node ~]# rpm -qa | grep -i gnocchi
openstack-gnocchi-api-4.0.2-1.el7.noarch
python-gnocchi-4.0.2-1.el7.noarch
openstack-gnocchi-metricd-4.0.2-1.el7.noarch
openstack-gnocchi-common-4.0.2-1.el7.noarch
python2-gnocchiclient-3.3.1-1.el7.noarch
openstack-gnocchi-indexer-sqlalchemy-4.0.2-1.el7.noarch
[root@node ~]# gnocchi --version
gnocchi 3.3.1
```

### How to reproduce your problem
Configure to use Ceph 12.2.2 as a storage and run `gnocchi-upgrade`

### What is the result that you get
```
2018-01-17 14:18:59,441 [10439] DEBUG    gnocchi.service: ********************************************************************************
2018-01-17 14:19:00,348 [10439] INFO     gnocchi.cli: Upgrading indexer <gnocchi.indexer.sqlalchemy.SQLAlchemyIndexer object at 0x1b61750>
2018-01-17 14:19:00,575 [10439] INFO     gnocchi.storage.common.ceph: Ceph storage backend use 'rados' python library
2018-01-17 14:19:00,650 [10439] CRITICAL root: Traceback (most recent call last):
  File "/bin/gnocchi-upgrade", line 10, in <module>
    sys.exit(upgrade())
  File "/usr/lib/python2.7/site-packages/gnocchi/cli.py", line 66, in upgrade
    s = storage.get_driver(conf)
  File "/usr/lib/python2.7/site-packages/gnocchi/storage/__init__.py", line 161, in get_driver
    conf.incoming)
  File "/usr/lib/python2.7/site-packages/gnocchi/storage/incoming/ceph.py", line 34, in __init__
    self.rados, self.ioctx = ceph.create_rados_connection(conf)
  File "/usr/lib/python2.7/site-packages/gnocchi/storage/common/ceph.py", line 68, in create_rados_connection
    conn.connect()
  File "rados.pyx", line 875, in rados.Rados.connect (/builddir/build/BUILD/ceph-12.2.2/build/src/pybind/rados/pyrex/rados.c:9759)
  File "rados.pyx", line 454, in rados.make_ex (/builddir/build/BUILD/ceph-12.2.2/build/src/pybind/rados/pyrex/rados.c:3197)
TypeError: InvalidArgumentError does not take keyword arguments
```
### What is result that you expected
Connect to the ceph cluster succeeded

### Gnocchi configuration
```
# grep -vE "^$|^#" /etc/gnocchi/gnocchi.conf 
[DEFAULT]
debug = True
[api]
auth_mode = keystone
[archive_policy]
[cors]
[database]
[healthcheck]
[incoming]
[indexer]
url = mysql+pymysql://gnocchi:Password123@mysql/gnocchi
[metricd]
[oslo_middleware]
[oslo_policy]
[statsd]
[storage]
driver = ceph
ceph_pool = metrics
ceph_username = metrics
ceph_secret = 7207e2dc-615e-461b-b176-33035209da44
ceph_keyring = /etc/ceph/ceph.client.metrics.keyring
ceph_conffile = /etc/ceph/ceph.conf
[keystone_authtoken]
auth_type = password
project_name = service
user_domain_name = default
auth_uri = http://keystone:5000
auth_url = http://keystone:35357
memcached_servers = memcached:11211
project_domain_name = default
username = gnocchi
password = Password123
```

**Comment by chungg** [comment]
can you list what version of python-rados and/or cradox you have?

**Comment by chungg** [comment]
oh err.. i'm guessing it's python-rados==12.2.2

**Comment by sileht** [comment]
Looks like a Ceph bug http://tracker.ceph.com/issues/22317

**Comment by sileht** [comment]
This is a bug in error translation, so the root cause is just that ceph servers are unreachable.

**Comment by gunph1ld** [comment]
@chungg `python-rados-12.2.2`
@sileht ceph servers are reachable
```
# ceph -n client.metrics --keyring=/etc/ceph/ceph.client.metrics.keyring health
HEALTH_OK
```

**Comment by gunph1ld** [comment]
Hmm, seems disabling `ceph_secret` helped to solve the problem.
It's definitely should be documented/fixed
