### ISSUE TITLE
Get timeout when using redis incoming storage

### ISSUE THREAD

**Issue by jeffrey4l** [gnocchixyz/gnocchi#683]
### Which version of Gnocchi are you using
4.1.2

### How to reproduce your problem

configure redis as incoming bug

```
[incoming]
driver = redis
redis_url = redis://admin:CYxrf43rAAKUE48aCzVQTYfpjiH8r417vlgsRhBo@172.16.50.4:26379?sentinel=kolla&sentinel_fallback=172.16.50.5:26379&sentinel_fallback=172.16.50.6:26379&socket_timeout=60&db=0
```

### What is the result that you get

timeout error will raise after the specified timeout value and this timeout is mandatory

if not configure the `socket_timeout`, gnocchi-api will raise following error

```
[Thu Jan 25 15:30:40.588457 2018] [:error] [pid 18] [remote 172.16.50.5:180] Traceback (most recent call last):
[Thu Jan 25 15:30:40.588477 2018] [:error] [pid 18] [remote 172.16.50.5:180]   File "/var/lib/kolla/venv/bin/gnocchi-api", line 22, in <module>
[Thu Jan 25 15:30:40.588517 2018] [:error] [pid 18] [remote 172.16.50.5:180]     application = app.load_app(api.prepare_service())
[Thu Jan 25 15:30:40.588527 2018] [:error] [pid 18] [remote 172.16.50.5:180]   File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/rest/app.py", line 99, in load_app
[Thu Jan 25 15:30:40.588545 2018] [:error] [pid 18] [remote 172.16.50.5:180]     incoming = gnocchi_incoming.get_driver(conf)
[Thu Jan 25 15:30:40.588552 2018] [:error] [pid 18] [remote 172.16.50.5:180]   File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/incoming/__init__.py", line 191, in get_driver
[Thu Jan 25 15:30:40.588564 2018] [:error] [pid 18] [remote 172.16.50.5:180]     conf.incoming, conf.metricd.greedy)
[Thu Jan 25 15:30:40.588669 2018] [:error] [pid 18] [remote 172.16.50.5:180]   File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/incoming/redis.py", line 28, in __init__
[Thu Jan 25 15:30:40.588734 2018] [:error] [pid 18] [remote 172.16.50.5:180]     self._client = redis.get_client(conf)
[Thu Jan 25 15:30:40.588794 2018] [:error] [pid 18] [remote 172.16.50.5:180]   File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/common/redis.py", line 115, in get_client
[Thu Jan 25 15:30:40.588848 2018] [:error] [pid 18] [remote 172.16.50.5:180]     socket_timeout=kwargs['socket_timeout'])
[Thu Jan 25 15:30:40.588906 2018] [:error] [pid 18] [remote 172.16.50.5:180] KeyError: 'socket_timeout'

```
if configure the `socket_timeout=60`, will get error from gnocchi-metricd
```
2018-01-25 16:32:28,607 [5210] ERROR    gnocchi.cli.metricd: Error while listening for new measures notification, retrying
Traceback (most recent call last):
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/cli/metricd.py", line 183, in _fill_sacks_to_process
    for sack in self.incoming.iter_on_sacks_to_process():
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/incoming/redis.py", line 128, in iter_on_sacks_to_process
    for message in p.listen():
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/redis/client.py", line 2248, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/redis/client.py", line 2183, in parse_response
    return self._execute(connection, connection.read_response)
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/redis/client.py", line 2165, in _execute
    return command(*args)
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/redis/sentinel.py", line 55, in read_response
    return super(SentinelManagedConnection, self).read_response()
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/redis/connection.py", line 139, in _read_from_socket
    raise TimeoutError("Timeout reading from socket")
TimeoutError: Timeout reading from socket
```

### What is result that you expected

gnocchi should run without any exception.

### other info

i found the exact the same issue on the redis-py issue page  https://github.com/andymccurdy/redis-py/issues/225#issuecomment-4063287 

it  recommend to use `socket_timeout=None`, so i think should we make the socket_timeout to None if it doesn't exist?

**Comment by jeffrey4l** [comment]
I change the code, and set the `socket_timeout=None`, then the error is gong.

**Comment by jeffrey4l** [comment]
after configured following parameters on the `redis_url`, which works

```
redis_url = redis://xxxxx&socket_timeout=60&retry_on_timeout=yes
```
