### ISSUE TITLE
Unable to install in python virtualenv on Ubuntu 16.04

### ISSUE THREAD

**Issue by embik** [gnocchixyz/gnocchi#824]
I'm unable to install Gnocchi by following the existing documentation. The `pip install` process crashes when used in a Python3 venv (I'm confining Gnocchi to its own virtual environment because I don't want to pollute the system's apt-managed python packages).

### Which version of Gnocchi are you using
Most recent from `pip install`, `4.2.1`.

### How to reproduce your problem
On up-to-date Ubuntu 16.04:
```
root:~# python3 -m venv venv
root:~# cd venv/
root:~/venv# source bin/activate
(venv) root:~/venv# pip install gnocchi[postgresql,ceph,keystone]
```

### What is the result that you get
```
Collecting gnocchi[ceph,keystone,postgresql]
  Using cached gnocchi-4.2.1-py2.py3-none-any.whl
Collecting ujson (from gnocchi[ceph,keystone,postgresql])
  Using cached ujson-1.35.tar.gz
Collecting PasteDeploy (from gnocchi[ceph,keystone,postgresql])
  Using cached PasteDeploy-1.5.2-py2.py3-none-any.whl
Collecting jsonpatch (from gnocchi[ceph,keystone,postgresql])
  Using cached jsonpatch-1.21-py2.py3-none-any.whl
Collecting six (from gnocchi[ceph,keystone,postgresql])
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting oslo.policy>=0.3.0 (from gnocchi[ceph,keystone,postgresql])
  Using cached oslo.policy-1.34.0-py2.py3-none-any.whl
Collecting Paste (from gnocchi[ceph,keystone,postgresql])
  Using cached Paste-2.0.3-py34-none-any.whl
Collecting stevedore (from gnocchi[ceph,keystone,postgresql])
  Using cached stevedore-1.28.0-py2.py3-none-any.whl
Collecting iso8601 (from gnocchi[ceph,keystone,postgresql])
  Using cached iso8601-0.1.12-py3-none-any.whl
Collecting daiquiri (from gnocchi[ceph,keystone,postgresql])
  Using cached daiquiri-1.3.0-py2.py3-none-any.whl
Collecting pytimeparse (from gnocchi[ceph,keystone,postgresql])
  Using cached pytimeparse-1.1.7-py2.py3-none-any.whl
Collecting WebOb>=1.4.1 (from gnocchi[ceph,keystone,postgresql])
  Using cached WebOb-1.7.4-py2.py3-none-any.whl
Collecting numpy>=1.9.0 (from gnocchi[ceph,keystone,postgresql])
  Using cached numpy-1.14.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting tooz>=1.38 (from gnocchi[ceph,keystone,postgresql])
  Using cached tooz-1.61.0-py2.py3-none-any.whl
Collecting cotyledon>=1.5.0 (from gnocchi[ceph,keystone,postgresql])
  Using cached cotyledon-1.6.8-py2.py3-none-any.whl
Collecting pbr (from gnocchi[ceph,keystone,postgresql])
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Collecting pecan>=0.9 (from gnocchi[ceph,keystone,postgresql])
  Using cached pecan-1.3.2.tar.gz
Collecting voluptuous>=0.8.10 (from gnocchi[ceph,keystone,postgresql])
  Using cached voluptuous-0.11.1-py2.py3-none-any.whl
Collecting oslo.config>=3.22.0 (from gnocchi[ceph,keystone,postgresql])
  Using cached oslo.config-5.2.0-py2.py3-none-any.whl
Collecting monotonic (from gnocchi[ceph,keystone,postgresql])
  Using cached monotonic-1.4-py2.py3-none-any.whl
Collecting pyparsing>=2.2.0 (from gnocchi[ceph,keystone,postgresql])
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting lz4>=0.9.0 (from gnocchi[ceph,keystone,postgresql])
  Using cached lz4-1.0.0.tar.gz
Collecting oslo.middleware>=3.22.0 (from gnocchi[ceph,keystone,postgresql])
  Using cached oslo.middleware-3.35.0-py2.py3-none-any.whl
Collecting cachetools (from gnocchi[ceph,keystone,postgresql])
  Using cached cachetools-2.0.1-py2.py3-none-any.whl
Collecting werkzeug (from gnocchi[ceph,keystone,postgresql])
  Using cached Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting tenacity>=4.6.0 (from gnocchi[ceph,keystone,postgresql])
  Using cached tenacity-4.9.0-py2.py3-none-any.whl
Collecting cradox>=1.2.0; extra == "ceph" (from gnocchi[ceph,keystone,postgresql])
  Using cached cradox-2.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    no previously-included directories found matching 'docs/_build'

    Installed /tmp/pip-build-zbsn4_gd/cradox/.eggs/Jinja2-2.10-py3.5.egg
    Searching for Cython!=0.28.0,!=0.28.1
    Reading https://pypi.python.org/simple/Cython/
    Best match: Cython 0.27.3
    Downloading https://pypi.python.org/packages/ee/2a/c4d2cdd19c84c32d978d18e9355d1ba9982a383de87d0fcb5928553d37f4/Cython-0.27.3.tar.gz#md5=6149238287d662bd5d5e572482252493
    Processing Cython-0.27.3.tar.gz
    Writing /tmp/easy_install-yqg6026e/Cython-0.27.3/setup.cfg
    Running Cython-0.27.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-yqg6026e/Cython-0.27.3/egg-dist-tmp-etffabv5
    Compiling /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Plex/Scanners.py because it changed.
    Compiling /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Plex/Actions.py because it changed.
    Compiling /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/Pythran.py because it changed.
    Compiling /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/Lexicon.py because it changed.
    Compiling /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/Scanning.py because it changed.
    Compiling /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/Parsing.py because it changed.
    Compiling /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/Visitor.py because it changed.
    Compiling /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/FlowControl.py because it changed.
    Compiling /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/Code.py because it changed.
    Compiling /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Runtime/refnanny.pyx because it changed.
    Compiling /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Tempita/_tempita.py because it changed.
    [ 1/11] Cythonizing /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/Code.py
    [ 2/11] Cythonizing /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/FlowControl.py
    [ 3/11] Cythonizing /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/Lexicon.py
    [ 4/11] Cythonizing /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/Parsing.py
    [ 5/11] Cythonizing /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/Pythran.py
    [ 6/11] Cythonizing /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/Scanning.py
    [ 7/11] Cythonizing /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Compiler/Visitor.py
    [ 8/11] Cythonizing /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Plex/Actions.py
    [ 9/11] Cythonizing /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Plex/Scanners.py
    [10/11] Cythonizing /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Runtime/refnanny.pyx
    [11/11] Cythonizing /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Tempita/_tempita.py
      File "build/bdist.linux-x86_64/egg/jinja2/asyncsupport.py", line 35
        yield event
                  ^
    SyntaxError: 'yield' inside async function

      File "build/bdist.linux-x86_64/egg/jinja2/asyncfilters.py", line 24
        yield item
                 ^
    SyntaxError: 'yield' inside async function

      File "/tmp/pip-build-zbsn4_gd/cradox/.eggs/Jinja2-2.10-py3.5.egg/jinja2/asyncsupport.py", line 35
        yield event
                  ^
    SyntaxError: 'yield' inside async function

      File "/tmp/pip-build-zbsn4_gd/cradox/.eggs/Jinja2-2.10-py3.5.egg/jinja2/asyncfilters.py", line 24
        yield item
                 ^
    SyntaxError: 'yield' inside async function

    Unable to find pgen, not compiling formal grammar.
    warning: no files found matching '2to3-fixers.txt'
    warning: no files found matching 'Doc/*'
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    /tmp/easy_install-yqg6026e/Cython-0.27.3/Cython/Plex/Scanners.c:19:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/venv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 161, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/root/venv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
        self.run_command(cmdname)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/venv/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 23, in run
        self.build()
      File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
        self.run_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/venv/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 49, in run
        _build_ext.run(self)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/root/venv/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 174, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-yqg6026e/Cython-0.27.3/setup.py", line 286, in <module>
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/root/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1087, in run_setup
        run_setup(setup_script, args)
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 246, in run_setup
        raise
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/root/venv/lib/python3.5/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/root/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-yqg6026e/Cython-0.27.3/setup.py", line 286, in <module>
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zbsn4_gd/cradox/setup.py", line 72, in <module>
        ext_modules=[Extension("cradox", ["cradox.pyx"], libraries=["rados"])],
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/root/venv/lib/python3.5/site-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/root/venv/lib/python3.5/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/root/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/root/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/root/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/root/venv/lib/python3.5/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/root/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 663, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/root/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 693, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/root/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 873, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/root/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/root/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1089, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zbsn4_gd/cradox/
You are using pip version 8.1.1, however version 9.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv) root:~/venv# pip --version
pip 8.1.1 from /root/venv/lib/python3.5/site-packages (python 3.5)
```

### What is the result that you expected
A successful installation of gnocchi

**Comment by chungg** [comment]
you need to setup your system itself. you're probably missing python-dev/python-devel packages... probably libffi-dev/libffi-devel as well

try:

apt-get install libffi-dev
apt-get install python3-dev

install build-essential if you dont' have it as well?

**Comment by embik** [comment]
Installed `build-essential` (already present though) `libffi-dev`, `python-dev`, `librados-dev` and `librados2` (because the next error message told me to). Looks like that fixed my issues.

It would be nice if the documentation had a list of packages required to run the official installation routine to simplify deployment though.
