### ISSUE TITLE
gnocchi-metricd raised error when running a performance test for gnocchi-api

### ISSUE THREAD

**Issue by jeffrey4l** [gnocchixyz/gnocchi#863]
### Which version of Gnocchi are you using
gnocchi 4.2.2
redis as incoming storage and coordinate backend
ceph jewel as backend storage

```
pip freeze | egrep "cradox|numpy|gnocchi"
cradox==2.0.5
gnocchi==4.2.1
gnocchiclient==3.3.1
numpy==1.13.1
```

### How to reproduce your problem

use the following command to test gnocchi performance.

https://github.com/pandas-dev/pandas/issues/13844 seems the same with this issue. But aren't we using numpy rather than pandas?

```
    parallel --progress -j 50 \
        python tools/duration_perf_test.py \
        --os-username admin \
        --os-tenant-name admin \
        --os-password 99Cloud18 \
        --os-auth-url http://172.18.22.180:35357/v2.0 \
        --gnocchi-url http://172.18.22.180:8041 \
        --result results/client{} \
        --metric-count=100 \
        --measure-count=100 \
        --batch-size=30 \
        ::: $(seq 0 50)
```

### What is the result that you get

Get following error message in `gnocchi-metricd.log`

```
2018-04-13 12:29:19,890 [62] ERROR    gnocchi.storage: Error processing new measures
Traceback (most recent call last):
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/storage/__init__.py", line 505, in process_new_measures
    self._compute_and_store_timeseries(metric, measures)
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/storage/__init__.py", line 580, in _compute_and_store_timeseries
    before_truncate_callback=_map_add_measures)
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/carbonara.py", line 344, in set_values
    before_truncate_callback(self)
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/storage/__init__.py", line 576, in _map_add_measures
    for aggregation in agg_methods))
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/utils.py", line 312, in parallel_map
    return list(executor.map(lambda args: fn(*args), list_of_args))
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/concurrent/futures/_base.py", line 605, in result_iterator
    yield future.result()
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/concurrent/futures/_base.py", line 429, in result
    return self.__get_result()
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/utils.py", line 312, in <lambda>
    return list(executor.map(lambda args: fn(*args), list_of_args))
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/storage/__init__.py", line 404, in _add_measures
    oldest_mutable_timestamp, oldest_point_to_keep)
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/storage/__init__.py", line 325, in _store_timeserie_split
    offset, data = split.serialize(key, compressed=write_full)
  File "/var/lib/kolla/venv/lib/python2.7/site-packages/gnocchi/carbonara.py", line 709, in serialize
    timestamps[0] = (self.first - start.key) / offset_div
```

### What is result that you expected

should be no error.

**Comment by chungg** [comment]
i think you missed pasting the actual error but yes, there is no pandas in gnocchi 4.2+.

**Comment by chungg** [comment]
oh, i'm guessing you hit #848

**Comment by jd** [comment]
I've just pushed 4.2.3 with the fix.

**Comment by jeffrey4l** [comment]
tested with 4.2.3. no errors now. thanks a lot.
