### ISSUE TITLE
centos 7 openstack-gnocchi-statsd-3.1.16-1.el7 too much locks on nfs

### ISSUE THREAD

**Issue by icassano** [gnocchixyz/gnocchi#913]
Hellom
I installed centos 7 openstack ocata with gnocchi.
The gnocchi backend is "file" and /var/lib/gnocchi is on netapp nfs.
Sometime a lot of locks are created on nfs and the statsd.log reports
the following:

```
2018-01-22 11:30:07.378 175808 ERROR trollius [-] Exception in callback _flush() at /usr/lib/python2.7/site-packages/gnocchi/statsd.py:179
handle: <TimerHandle when=1041148.21803 _flush() at /usr/lib/python2.7/site-packages/gnocchi/statsd.py:179>
2018-01-22 11:30:07.378 175808 ERROR trollius Traceback (most recent call last):
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/trollius/events.py", line 136, in _run
2018-01-22 11:30:07.378 175808 ERROR trollius     self._callback(*self._args)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/gnocchi/statsd.py", line 181, in _flush
2018-01-22 11:30:07.378 175808 ERROR trollius     stats.flush()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/gnocchi/statsd.py", line 93, in flush
2018-01-22 11:30:07.378 175808 ERROR trollius     with_metrics=True)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 151, in wrapper
2018-01-22 11:30:07.378 175808 ERROR trollius     ectxt.value = e.inner_exc
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-01-22 11:30:07.378 175808 ERROR trollius     self.force_reraise()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-01-22 11:30:07.378 175808 ERROR trollius     six.reraise(self.type_, self.value, self.tb)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 139, in wrapper
2018-01-22 11:30:07.378 175808 ERROR trollius     return f(*args, **kwargs)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/gnocchi/indexer/sqlalchemy.py", line 932, in get_resource
2018-01-22 11:30:07.378 175808 ERROR trollius     session, resource_type)['resource']
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/gnocchi/indexer/sqlalchemy.py", line 574, in _resource_type_to_mappers
2018-01-22 11:30:07.378 175808 ERROR trollius     resource_type = self._get_resource_type(session, name)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/gnocchi/indexer/sqlalchemy.py", line 469, in _get_resource_type
2018-01-22 11:30:07.378 175808 ERROR trollius     resource_type = session.query(ResourceType).get(name)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 831, in get
2018-01-22 11:30:07.378 175808 ERROR trollius     return self._get_impl(ident, loading.load_on_ident)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 864, in _get_impl
2018-01-22 11:30:07.378 175808 ERROR trollius     return fallback_fn(self, key)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 219, in load_on_ident
2018-01-22 11:30:07.378 175808 ERROR trollius     return q.one()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2693, in one
2018-01-22 11:30:07.378 175808 ERROR trollius     ret = list(self)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
2018-01-22 11:30:07.378 175808 ERROR trollius     return self._execute_and_instances(context)
```

Regards

**Comment by jd** [comment]
Your traceback is not complete.

**Comment by jd** [comment]
Duplicated in https://github.com/gnocchixyz/gnocchi/issues/913
