### ISSUE TITLE
centos 7 openstack-gnocchi-statsd-3.1.16-1.el7 too much locks on nfs

### ISSUE THREAD

**Issue by icassano** [gnocchixyz/gnocchi#914]
Hello
I installed centos 7 openstack ocata with gnocchi.
The gnocchi backend is "file" and /var/lib/gnocchi is on netapp nfs.
Indexer ins on mariadb and seems it lost connection with it also if it is available.
Sometime a lot of locks are created on nfs and the statsd.log reports
the following:

```
2018-01-22 11:30:07.378 175808 ERROR trollius [-] Exception in callback _flush() at /usr/lib/python2.7/site-packages/gnocchi/statsd.py:179
handle: <TimerHandle when=1041148.21803 _flush() at /usr/lib/python2.7/site-packages/gnocchi/statsd.py:179>
2018-01-22 11:30:07.378 175808 ERROR trollius Traceback (most recent call last):
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/trollius/events.py", line 136, in _run
2018-01-22 11:30:07.378 175808 ERROR trollius     self._callback(*self._args)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/gnocchi/statsd.py", line 181, in _flush
2018-01-22 11:30:07.378 175808 ERROR trollius     stats.flush()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/gnocchi/statsd.py", line 93, in flush
2018-01-22 11:30:07.378 175808 ERROR trollius     with_metrics=True)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 151, in wrapper
2018-01-22 11:30:07.378 175808 ERROR trollius     ectxt.value = e.inner_exc
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2018-01-22 11:30:07.378 175808 ERROR trollius     self.force_reraise()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2018-01-22 11:30:07.378 175808 ERROR trollius     six.reraise(self.type_, self.value, self.tb)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 139, in wrapper
2018-01-22 11:30:07.378 175808 ERROR trollius     return f(*args, **kwargs)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/gnocchi/indexer/sqlalchemy.py", line 932, in get_resource
2018-01-22 11:30:07.378 175808 ERROR trollius     session, resource_type)['resource']
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/gnocchi/indexer/sqlalchemy.py", line 574, in _resource_type_to_mappers
2018-01-22 11:30:07.378 175808 ERROR trollius     resource_type = self._get_resource_type(session, name)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/gnocchi/indexer/sqlalchemy.py", line 469, in _get_resource_type
2018-01-22 11:30:07.378 175808 ERROR trollius     resource_type = session.query(ResourceType).get(name)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 831, in get
2018-01-22 11:30:07.378 175808 ERROR trollius     return self._get_impl(ident, loading.load_on_ident)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 864, in _get_impl
2018-01-22 11:30:07.378 175808 ERROR trollius     return fallback_fn(self, key)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 219, in load_on_ident
2018-01-22 11:30:07.378 175808 ERROR trollius     return q.one()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2693, in one
2018-01-22 11:30:07.378 175808 ERROR trollius     ret = list(self)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
2018-01-22 11:30:07.378 175808 ERROR trollius     return self._execute_and_instances(context)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2749, in _execute_and_instances
2018-01-22 11:30:07.378 175808 ERROR trollius     close_with_result=True)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2740, in _connection_from_session
2018-01-22 11:30:07.378 175808 ERROR trollius     **kw)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 905, in connection
2018-01-22 11:30:07.378 175808 ERROR trollius     execution_options=execution_options)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 910, in _connection_for_bind
2018-01-22 11:30:07.378 175808 ERROR trollius     engine, execution_options)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
2018-01-22 11:30:07.378 175808 ERROR trollius     conn = bind.contextual_connect()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2041, in contextual_connect
2018-01-22 11:30:07.378 175808 ERROR trollius     **kwargs)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 92, in __init__
2018-01-22 11:30:07.378 175808 ERROR trollius     self.dispatch.engine_connect(self, self.__branch)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
2018-01-22 11:30:07.378 175808 ERROR trollius     fn(*args, **kw)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py", line 80, in _connect_ping_listener
2018-01-22 11:30:07.378 175808 ERROR trollius     connection.scalar(select([1]))
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 844, in scalar
2018-01-22 11:30:07.378 175808 ERROR trollius     return self.execute(object, *multiparams, **params).scalar()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
2018-01-22 11:30:07.378 175808 ERROR trollius     return meth(self, multiparams, params)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
2018-01-22 11:30:07.378 175808 ERROR trollius     return connection._execute_clauseelement(self, multiparams, params)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
2018-01-22 11:30:07.378 175808 ERROR trollius     compiled_sql, distilled_params
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
2018-01-22 11:30:07.378 175808 ERROR trollius     None, None)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1337, in _handle_dbapi_exception
2018-01-22 11:30:07.378 175808 ERROR trollius     util.raise_from_cause(newraise, exc_info)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
2018-01-22 11:30:07.378 175808 ERROR trollius     reraise(type(exception), exception, tb=exc_tb)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
2018-01-22 11:30:07.378 175808 ERROR trollius     conn = self._revalidate_connection()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 393, in _revalidate_connection
2018-01-22 11:30:07.378 175808 ERROR trollius     self.__connection = self.engine.raw_connection(_connection=self)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2104, in raw_connection
2018-01-22 11:30:07.378 175808 ERROR trollius     self.pool.unique_connection, _connection)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2080, in _wrap_pool_connect
2018-01-22 11:30:07.378 175808 ERROR trollius     util.reraise(*sys.exc_info())
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
2018-01-22 11:30:07.378 175808 ERROR trollius     return fn()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 318, in unique_connection
2018-01-22 11:30:07.378 175808 ERROR trollius     return _ConnectionFairy._checkout(self)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
2018-01-22 11:30:07.378 175808 ERROR trollius     fairy = _ConnectionRecord.checkout(pool)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 485, in checkout
2018-01-22 11:30:07.378 175808 ERROR trollius     rec.checkin()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
2018-01-22 11:30:07.378 175808 ERROR trollius     compat.reraise(exc_type, exc_value, exc_tb)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 482, in checkout
2018-01-22 11:30:07.378 175808 ERROR trollius     dbapi_connection = rec.get_connection()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 563, in get_connection
2018-01-22 11:30:07.378 175808 ERROR trollius     self.connection = self.__connect()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
2018-01-22 11:30:07.378 175808 ERROR trollius     connection = self.__pool._invoke_creator(self)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
2018-01-22 11:30:07.378 175808 ERROR trollius     return dialect.connect(*cargs, **cparams)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
2018-01-22 11:30:07.378 175808 ERROR trollius     return self.dbapi.connect(*cargs, **cparams)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
2018-01-22 11:30:07.378 175808 ERROR trollius     return Connection(*args, **kwargs)
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 694, in __init__
2018-01-22 11:30:07.378 175808 ERROR trollius     self.connect()
2018-01-22 11:30:07.378 175808 ERROR trollius   File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 947, in connect
2018-01-22 11:30:07.378 175808 ERROR trollius     raise exc
2018-01-22 11:30:07.378 175808 ERROR trollius DBConnectionError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '10.138.184.11' ([Errno 111] Connection refused)") [SQL: u'SELECT 1']
2018-01-22 11:30:07.378 175808 ERROR trollius
```

**Comment by jd** [comment]
`Can't connect to MySQL server on '10.138.184.11' ([Errno 111] Connection refused)`

It sounds like your MySQL server does not work at some point. Maybe you need to increase the number of concurrent connections?
Does not seem related to NFS anyway.

**Comment by icassano** [comment]
Manu thanks

Il Gio 14 Giu 2018 11:19 Julien Danjou <notifications@github.com> ha
scritto:

**Comment by chungg** [comment]
can you list your tooz version. there was a but in tooz a while back which opened a lot of sql connections so maybe upgrade that.

**Comment by icassano** [comment]
OK.
I will do it.
Thanks

2018-06-14 17:36 GMT+02:00 gord chung <notifications@github.com>:
