### ISSUE TITLE
xattr is broken

### ISSUE THREAD

**Issue by sileht** [gnocchixyz/gnocchi#951]
xattr 0.9.4 is broken, xattr developer have remove the tarball but keep a broken whell instead of releasing a fixed version.

```
collecting xattr>=0.4 (from swift)
  Using cached https://files.pythonhosted.org/packages/68/f0/9401a4e6b108c68cbe4a11f055fb72c89cb605eab2be871b06616fce7017/xattr-0.9.4.tar.gz
    Complete output from command python setup.py egg_info:
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    pycparser.ply.__pycache__.lex.cpython-37: module references __file__
    pycparser.ply.__pycache__.lex.cpython-37: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-37: module references __file__
    pycparser.ply.__pycache__.yacc.cpython-37: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-37: module MAY be using inspect.stack
    pycparser.ply.__pycache__.ygen.cpython-37: module references __file__
    
    Installed /tmp/pip-install-org9oqt1/xattr/.eggs/pycparser-2.18-py3.7.egg
    Warning: 'classifiers' should be a list, got type 'filter'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-org9oqt1/xattr/setup.py", line 56, in <module>
        zip_safe=False,
      File "/home/tester/src/.tox/py37-mysql/lib/python3.7/site-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/tester/src/.tox/py37-mysql/lib/python3.7/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/home/tester/src/.tox/py37-mysql/lib/python3.7/site-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-install-org9oqt1/xattr/.eggs/cffi-1.11.5-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 204, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-install-org9oqt1/xattr/.eggs/cffi-1.11.5-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-install-org9oqt1/xattr/.eggs/cffi-1.11.5-py3.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "xattr/lib_build.py", line 7, in <module>
        with open(os.path.join(PATH, 'lib_build.h')) as hf:
    FileNotFoundError: [Errno 2] No such file or directory: 'xattr/lib_build.h'
```

**Comment by sileht** [comment]
Hum they just upload a new tarball for 0.9.4...
