### ISSUE TITLE
Gnocchi.xyz is not built anymore

### ISSUE THREAD

**Issue by jd** [gnocchixyz/gnocchi#953]
https://gnocchi.xyz/build-logs/gnocchi.log

```
docs-gnocchi.xyz create: /srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz
docs-gnocchi.xyz installdeps: -e, .[test,file,postgresql,doc], doc8, sphinxcontrib-versioning, pbr, WebOb<1.8, scipy, pandas, lz4>=0.9,<=0.13, oslotest, oslosphinx, retrying
ERROR: invocation failed (exit code 1), logfile: /srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz/log/docs-gnocchi.xyz-1.log
ERROR: actionid: docs-gnocchi.xyz
msg: getenv
cmdargs: ['/srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz/bin/pip', 'install', '-e', '.[test,file,postgresql,doc]', 'doc8', 'sphinxcontrib-versioning', 'pbr', 'WebOb<1.8', 'scipy', 'pandas', 'lz4>=0.9,<=0.13', 'oslotest', 'oslosphinx', 'retrying']
env: {'LANG': 'en_US.UTF-8', 'VIRTUAL_ENV': '/srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz', 'SHELL': '/bin/sh', 'XDG_RUNTIME_DIR': '/run/user/1000', 'SHLVL': '4', 'OLDPWD': '/srv/gnocchi_builder', 'PWD': '/srv/gnocchi_builder/gnocchi', 'PYTHONHASHSEED': '3708915585', 'LOGNAME': 'gnocchi_builder', 'USER': 'gnocchi_builder', 'MANPATH': '/opt/rh/git19/root/usr/share/man:', 'PATH': '/srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz/bin:/opt/rh/git19/root/usr/bin:/usr/bin:/bin', 'X_SCLS': 'git19 ', 'HOME': '/srv/gnocchi_builder', 'GNOCCHI_TEST_DEBUG': '1', 'XDG_SESSION_ID': '9950', '_': '/usr/bin/tox', 'GNOCCHI_STORAGE_DEPS': 'file'}

Obtaining file:///srv/gnocchi_builder/gnocchi
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/srv/gnocchi_builder/gnocchi/setup.py", line 48, in <module>
        cmdclass=cmdclass,
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz/lib/python2.7/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz/lib/python2.7/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz/lib/python2.7/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1115, in best_match
        dist = working_set.find(req)
      File "/srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (setuptools 28.8.0 (/srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz/lib/python2.7/site-packages), Requirement.parse('setuptools>=30.3.0'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /srv/gnocchi_builder/gnocchi/
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

ERROR: could not install deps [-e, .[test,file,postgresql,doc], doc8, sphinxcontrib-versioning, pbr, WebOb<1.8, scipy, pandas, lz4>=0.9,<=0.13, oslotest, oslosphinx, retrying]; v = InvocationError('/srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz/bin/pip install -e .[test,file,postgresql,doc] doc8 sphinxcontrib-versioning pbr WebOb<1.8 scipy pandas lz4>=0.9,<=0.13 oslotest oslosphinx retrying (see /srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz/log/docs-gnocchi.xyz-1.log)', 1)
___________________________________ summary ____________________________________
ERROR:   docs-gnocchi.xyz: could not install deps [-e, .[test,file,postgresql,doc], doc8, sphinxcontrib-versioning, pbr, WebOb<1.8, scipy, pandas, lz4>=0.9,<=0.13, oslotest, oslosphinx, retrying]; v = InvocationError('/srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz/bin/pip install -e .[test,file,postgresql,doc] doc8 sphinxcontrib-versioning pbr WebOb<1.8 scipy pandas lz4>=0.9,<=0.13 oslotest oslosphinx retrying (see /srv/gnocchi_builder/gnocchi/.tox/docs-gnocchi.xyz/log/docs-gnocchi.xyz-1.log)', 1)
```

**Comment by jd** [comment]
There are several problems. Among them, we need Sphinx 1.6.0 (for reno) and sphinxcontrib-versioning does not support it see https://github.com/Robpol86/sphinxcontrib-versioning/issues/56.

It seems sphinxcontrib-versioning is not maintained anymore. I'll reach the maintainer.
