### ISSUE TITLE
gnocchi 4.3.0 oslo_utils/tooz issue

### ISSUE THREAD

**Issue by tobias-urdin** [gnocchixyz/gnocchi#979]
gnocchi 4.3.0 with openstack rocky oslo.utils 3.36.4 and tooz 1.62.0

python-oslo-utils-lang-3.36.4-1.el7.noarch
gnocchi-api-4.3.0-1.el7.noarch
gnocchi-common-4.3.0-1.el7.noarch
python2-oslo-utils-3.36.4-1.el7.noarch
python-gnocchi-4.3.0-1.el7.noarch
python2-gnocchiclient-7.0.4-1.el7.noarch
python2-tooz-1.62.0-1.el7.noarch
gnocchi-metricd-4.3.0-1.el7.noarch

redis as coordinator
python-redis-2.10.3-1.el7.noarch

coordination_url=redis://127.0.0.1:6379
```
$telnet 127.0.0.1 6379
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
quit
+OK
Connection closed by foreign host.
```
```
[Tue Sep 25 16:12:42.465254 2018] [:error] [pid 29265]  Exception in thread Thread-1 (most likely raised during interpreter shutdown):
[Tue Sep 25 16:12:42.465214 2018] [:error] [pid 29265] Exception in thread Thread-2 (most likely raised during interpreter shutdown):
[Tue Sep 25 16:12:42.465300 2018] [:error] [pid 29265] Traceback (most recent call last):
[Tue Sep 25 16:12:42.465309 2018] [:error] [pid 29265] Traceback (most recent call last):
[Tue Sep 25 16:12:42.465324 2018] [:error] [pid 29265]   File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
[Tue Sep 25 16:12:42.465336 2018] [:error] [pid 29265]   File "/usr/lib64/python2.7/threading.py", line 765, in run
[Tue Sep 25 16:12:42.465352 2018] [:error] [pid 29265]   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 250, in wrapper
[Tue Sep 25 16:12:42.465372 2018] [:error] [pid 29265]   File "/usr/lib/python2.7/site-packages/tooz/coordination.py", line 186, in _beat_forever_until_stopped
[Tue Sep 25 16:12:42.465385 2018] [:error] [pid 29265] <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'StopWatch'
[Tue Sep 25 16:12:42.465676 2018] [:error] [pid 29265]   File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
[Tue Sep 25 16:12:42.465691 2018] [:error] [pid 29265]   File "/usr/lib64/python2.7/threading.py", line 765, in run
[Tue Sep 25 16:12:42.465701 2018] [:error] [pid 29265]   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 250, in wrapper
[Tue Sep 25 16:12:42.465710 2018] [:error] [pid 29265]   File "/usr/lib/python2.7/site-packages/tooz/coordination.py", line 186, in _beat_forever_until_stopped
[Tue Sep 25 16:12:42.465720 2018] [:error] [pid 29265] <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'StopWatch'
```

**Comment by sileht** [comment]
What is the daemon where that occurs ? api or metricd ?

**Comment by tobias-urdin** [comment]
the API running in mod_wsgi

**Comment by jd** [comment]
This is something we should actually fix in tooz. The heartbeat is a daemonized daemon that should just stop by itself when the interpreter is shutdown without trying to do fancy stuff and fail (like here). The retry code from oslo_utils is guilty there.

**Comment by jd** [comment]
Fix for tooz https://review.openstack.org/608181

**Comment by tobias-urdin** [comment]
Closing as it's fixed in Tooz by @jd and doesn't seem to be a issue that requires backport. Thanks for the fix!
